-- =====================================================================
--  SISTEM PENDAFTARAN LOMBA LAYANGAN  ·  pembaruan ke MULTI-EVENT
--  Versi 3.0 — Oktober 2026
-- ---------------------------------------------------------------------
--  SEBELUM MENJALANKAN: jalankan dulu cadangan-sebelum-multi-event.sql
--
--  CARA PAKAI
--   1. Supabase Dashboard → SQL Editor → New query
--   2. Paste SELURUH isi file ini → Run
--   3. Lihat tabel "cek multi-event" di panel hasil: semua baris harus ✅
--
--  Yang dilakukan file ini:
--   · membuat tabel event, admin event, dan pengaturan situs (halaman depan)
--   · menambah kolom event_id ke semua tabel lomba
--   · data yang sudah ada menjadi EVENT PERTAMA (tidak ada yang dihapus)
--   · email di lomba_admin menjadi SUPER ADMIN (bisa membuka semua event)
--   · fungsi & aturan keamanan diperbarui: admin event hanya bisa
--     membuka data event yang ditugaskan kepadanya
--
--  Halaman versi lama tetap berjalan (memakai event pertama) sampai
--  index.html versi multi-event dipasang. Aman dijalankan ulang.
-- =====================================================================


-- ---------------------------------------------------------------------
-- BAGIAN 1 · TABEL BARU
-- ---------------------------------------------------------------------
create table if not exists public.lomba_event (
  id          bigint generated by default as identity primary key,
  slug        text not null unique,
  tampil      boolean not null default true,
  created_at  timestamptz not null default now()
);
do $$ begin
  alter table public.lomba_event add constraint lomba_event_slug_chk
    check (slug ~ '^[a-z0-9][a-z0-9-]{1,38}[a-z0-9]$' and slug not in ('admin', 'panitia', 'semua', 'tiket'));
exception when duplicate_object then null; end $$;

-- Email admin (panitia) per event. Super admin tetap di tabel lomba_admin.
create table if not exists public.lomba_event_admin (
  event_id    bigint not null references public.lomba_event(id),
  email       text not null check (email = lower(btrim(email)) and email ~ '^[^@\s]+@[^@\s]+\.[^@\s]+$'),
  created_at  timestamptz not null default now(),
  primary key (event_id, email)
);
create index if not exists lomba_event_admin_email_idx on public.lomba_event_admin (email);

-- Pengaturan situs = halaman depan semua event (hanya 1 baris)
create table if not exists public.lomba_situs (
  id          int primary key default 1 check (id = 1),
  nama        text not null default 'Lomba Layangan Bali',
  judul       text not null default 'Semua lomba layangan, satu tempat daftar.',
  teks        text not null default 'Pilih event, isi data layangan, transfer, dan unggah bukti. Nomor & jadwal terbang langsung terlihat.',
  logo_url    text not null default '',
  bg_url      text not null default '',
  updated_at  timestamptz not null default now()
);
insert into public.lomba_situs (id) values (1) on conflict (id) do nothing;

-- Event pertama = data yang sudah ada (kode alamat dari nama event)
do $$
declare
  v_nama text;
  v_slug text;
begin
  if exists (select 1 from public.lomba_event) then
    return;
  end if;
  select nama_event into v_nama from public.lomba_pengaturan order by id limit 1;
  v_slug := regexp_replace(lower(coalesce(v_nama, '')), '[^a-z0-9]+', '-', 'g');
  v_slug := regexp_replace(left(regexp_replace(v_slug, '^-+', ''), 40), '-+$', '');
  if v_slug is null or length(v_slug) < 3 or v_slug in ('admin', 'panitia', 'semua', 'tiket') then
    v_slug := 'event-pertama';
  end if;
  insert into public.lomba_event (slug) values (v_slug);
end $$;

-- Event bawaan untuk halaman/data lama yang belum menyebut event
create or replace function public.lomba_event_default()
returns bigint
language sql
stable
security definer
set search_path = public
as $$
  select min(id) from public.lomba_event;
$$;


-- ---------------------------------------------------------------------
-- BAGIAN 2 · KOLOM event_id DI SEMUA TABEL LOMBA
-- ---------------------------------------------------------------------
do $$
declare
  t text;
begin
  foreach t in array array['lomba_pengaturan', 'lomba_jenis', 'lomba_hari', 'lomba_sesi', 'lomba_seri', 'lomba_pendaftaran']
  loop
    execute format('alter table public.%I add column if not exists event_id bigint default public.lomba_event_default()', t);
    execute format('update public.%I set event_id = public.lomba_event_default() where event_id is null', t);
    execute format('alter table public.%I alter column event_id set default public.lomba_event_default()', t);
    execute format('alter table public.%I alter column event_id set not null', t);
    begin
      execute format('alter table public.%I add constraint %I foreign key (event_id) references public.lomba_event(id)', t, t || '_event_fkey');
    exception when duplicate_object then null;
    end;
    execute format('create index if not exists %I on public.%I (event_id)', t || '_event_idx', t);
  end loop;
end $$;

-- Pengaturan: dulu hanya 1 baris (id = 1), sekarang 1 baris per event
alter table public.lomba_pengaturan drop constraint if exists lomba_pengaturan_id_check;
create sequence if not exists public.lomba_pengaturan_id_seq owned by public.lomba_pengaturan.id;
select setval('public.lomba_pengaturan_id_seq', greatest((select coalesce(max(id), 1) from public.lomba_pengaturan), 1));
alter table public.lomba_pengaturan alter column id set default nextval('public.lomba_pengaturan_id_seq');
create unique index if not exists lomba_pengaturan_event_uidx on public.lomba_pengaturan (event_id);
alter table public.lomba_pengaturan add column if not exists tanggal_mulai   date;
alter table public.lomba_pengaturan add column if not exists tanggal_selesai date;
-- flyer event (gambar A4 tegak) untuk halaman depan
alter table public.lomba_pengaturan add column if not exists flyer_url text not null default '';
-- tanggal event pertama diambil dari jadwal yang sudah ada
update public.lomba_pengaturan st
   set tanggal_mulai   = x.mulai,
       tanggal_selesai = x.akhir
  from (select h.event_id, min(h.tanggal) as mulai, max(h.tanggal) as akhir
          from public.lomba_hari h where h.tanggal is not null group by h.event_id) x
 where x.event_id = st.event_id and st.tanggal_mulai is null;

-- Jenis layangan: kode unik PER EVENT (dua event boleh punya jenis "bebean-plastik")
do $$
declare
  r record;
begin
  if exists (select 1 from pg_constraint
              where conrelid = 'public.lomba_jenis'::regclass and contype = 'p' and array_length(conkey, 1) = 2) then
    return;   -- sudah diubah
  end if;
  for r in select conname, conrelid::regclass as tbl from pg_constraint
            where confrelid = 'public.lomba_jenis'::regclass and contype = 'f'
  loop
    execute format('alter table %s drop constraint %I', r.tbl, r.conname);
  end loop;
  alter table public.lomba_jenis drop constraint lomba_jenis_pkey;
  alter table public.lomba_jenis add constraint lomba_jenis_pkey primary key (event_id, kode);
  alter table public.lomba_seri add constraint lomba_seri_jenis_fkey
    foreign key (event_id, jenis) references public.lomba_jenis(event_id, kode) on update cascade;
  alter table public.lomba_pendaftaran add constraint lomba_pendaftaran_jenis_fkey
    foreign key (event_id, jenis) references public.lomba_jenis(event_id, kode) on update cascade;
end $$;

-- Nomor layangan unik per JENIS di dalam EVENT yang sama
drop index if exists public.lomba_pendaftaran_nomor_uidx;
create unique index if not exists lomba_pendaftaran_nomor_ev_uidx
  on public.lomba_pendaftaran (event_id, jenis, nomor_layangan)
  where nomor_layangan is not null and status in ('menunggu', 'terkonfirmasi');


-- ---------------------------------------------------------------------
-- BAGIAN 3 · PERAN: SUPER ADMIN & ADMIN EVENT
-- ---------------------------------------------------------------------
-- email akun yang sedang login (hanya yang sudah terkonfirmasi)
create or replace function public.lomba_email_saya()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select lower(u.email) from auth.users u
   where u.id = auth.uid() and u.email_confirmed_at is not null;
$$;

-- super admin = email di tabel lomba_admin
create or replace function public.lomba_is_super()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (select 1 from public.lomba_admin a where lower(a.email) = public.lomba_email_saya());
$$;

-- boleh mengelola event ini? (super admin, atau admin yang ditugaskan)
create or replace function public.lomba_boleh_event(p_event bigint)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.lomba_is_super()
      or exists (select 1 from public.lomba_event_admin ea
                  where ea.event_id = p_event and ea.email = public.lomba_email_saya());
$$;

-- admin event mana pun (dipakai untuk akses gambar & cek login)
create or replace function public.lomba_is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.lomba_is_super()
      or exists (select 1 from public.lomba_event_admin ea where ea.email = public.lomba_email_saya());
$$;

create or replace function public.lomba_peran()
returns json
language sql
stable
security definer
set search_path = public
as $$
  select case when public.lomba_email_saya() is null then null
    else json_build_object('email', public.lomba_email_saya(),
                           'peran', case when public.lomba_is_super() then 'super' else 'panitia' end) end;
$$;


-- ---------------------------------------------------------------------
-- BAGIAN 4 · ATURAN OTOMATIS (TRIGGER) — sadar event
-- ---------------------------------------------------------------------
-- event sebuah baris tidak boleh dipindah
create or replace function public.lomba_trg_event_tetap()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if new.event_id is distinct from old.event_id then
    raise exception 'EVENT_TIDAK_BOLEH_DIPINDAH';
  end if;
  return new;
end;
$$;
do $$
declare
  t text;
begin
  foreach t in array array['lomba_pengaturan', 'lomba_jenis', 'lomba_hari', 'lomba_sesi', 'lomba_seri', 'lomba_pendaftaran']
  loop
    execute format('drop trigger if exists %I on public.%I', t || '_event_tetap', t);
    execute format('create trigger %I before update of event_id on public.%I for each row execute function public.lomba_trg_event_tetap()', t || '_event_tetap', t);
  end loop;
end $$;

-- nama, tanggal & lokasi event hanya boleh diubah super admin
create or replace function public.lomba_trg_pengaturan()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is not null and not public.lomba_is_super()
     and (new.nama_event is distinct from old.nama_event
          or new.lokasi is distinct from old.lokasi
          or new.tanggal_mulai is distinct from old.tanggal_mulai
          or new.tanggal_selesai is distinct from old.tanggal_selesai) then
    raise exception 'BUKAN_SUPER_ADMIN';
  end if;
  if new.tanggal_selesai is not null and new.tanggal_mulai is not null and new.tanggal_selesai < new.tanggal_mulai then
    raise exception 'TANGGAL_TIDAK_VALID';
  end if;
  return new;
end;
$$;
drop trigger if exists lomba_pengaturan_bu on public.lomba_pengaturan;
create trigger lomba_pengaturan_bu before update on public.lomba_pengaturan
  for each row execute function public.lomba_trg_pengaturan();

-- hari & seri (blok waktu): rapikan nama; seri ikut event hari-nya
create or replace function public.lomba_trg_sesi_sinkron()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_ev bigint;
begin
  new.nama := btrim(coalesce(new.nama, ''));
  if new.nama = '' then
    raise exception 'DATA_TIDAK_LENGKAP';
  end if;
  if tg_table_name = 'lomba_sesi' then
    select h.event_id into v_ev from public.lomba_hari h where h.id = new.hari_id;
    if v_ev is null then
      raise exception 'SERI_TIDAK_VALID';
    end if;
    new.event_id := v_ev;
  end if;
  return new;
end;
$$;

-- grup (lomba_seri): ikut event dari seri/hari-nya; nama, tanggal, jam & kuota otomatis
create or replace function public.lomba_trg_seri()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_sesi  text;
  v_mulai time;
  v_akhir time;
  v_tgl   date;
  v_ev    bigint;
begin
  if new.sesi_id is not null then
    select s.nama, s.jam_mulai, s.jam_selesai, h.tanggal, h.event_id
      into v_sesi, v_mulai, v_akhir, v_tgl, v_ev
      from public.lomba_sesi s join public.lomba_hari h on h.id = s.hari_id
     where s.id = new.sesi_id;
    if not found then
      raise exception 'SERI_TIDAK_VALID';
    end if;
    new.event_id := v_ev;
    new.huruf := upper(btrim(coalesce(new.huruf, '')));
    if new.huruf = '' then
      raise exception 'DATA_TIDAK_LENGKAP';
    end if;
    new.nama        := 'Seri ' || v_sesi || ' · ' || new.huruf;
    new.tanggal     := v_tgl;
    new.jam_mulai   := v_mulai;
    new.jam_selesai := v_akhir;
    new.tutup := coalesce((select array_agg(distinct x order by x)
                             from unnest(new.tutup) x where x between 1 and new.kotak), '{}');
    new.kuota := greatest(0, new.kotak - cardinality(new.tutup));
    if tg_op = 'UPDATE'
       and (new.kotak is distinct from old.kotak or new.tutup is distinct from old.tutup)
       and exists (
         select 1 from public.lomba_pendaftaran p
          where p.seri_id = new.id and p.kotak is not null
            and p.status in ('menunggu', 'terkonfirmasi')
            and (p.kotak > new.kotak or p.kotak = any(new.tutup))) then
      raise exception 'KOTAK_TERISI';
    end if;
  end if;

  new.nama := btrim(coalesce(new.nama, ''));
  if new.nama = '' then
    raise exception 'DATA_TIDAK_LENGKAP';
  end if;
  if tg_op = 'UPDATE' and new.jenis is distinct from old.jenis
     and exists (select 1 from public.lomba_pendaftaran where seri_id = old.id) then
    raise exception 'SERI_ADA_PESERTA';
  end if;
  return new;
end;
$$;

-- pendaftaran: ikut event grupnya; harga, kuota, kotak & nomor dihitung per event
create or replace function public.lomba_trg_pendaftaran()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_seri    public.lomba_seri%rowtype;
  v_terisi  int;
  v_cek     boolean;
  v_k       int;
begin
  -- 1) rapikan & validasi data dasar
  new.nama_sekha    := btrim(coalesce(new.nama_sekha, ''));
  new.alamat        := btrim(coalesce(new.alamat, ''));
  new.nama_rekening := btrim(coalesce(new.nama_rekening, ''));
  new.no_wa         := public.lomba_normalisasi_wa(new.no_wa);
  if new.no_wa is null then
    raise exception 'WA_TIDAK_VALID';
  end if;
  if new.nama_sekha = '' or new.alamat = '' or new.nama_rekening = '' then
    raise exception 'DATA_TIDAK_LENGKAP';
  end if;

  -- 2) jenis diganti → harga mengikuti jenis baru; pindah grup → kotak dipilih ulang
  if tg_op = 'UPDATE' and new.jenis is distinct from old.jenis then
    new.harga := null;
  end if;
  if tg_op = 'UPDATE' and new.seri_id is distinct from old.seri_id
     and new.kotak is not distinct from old.kotak then
    new.kotak := null;
  end if;

  -- 3) grup harus ada, sesuai jenis + cek kuota (baris grup dikunci agar antre)
  v_cek := new.status in ('menunggu', 'terkonfirmasi')
           and (tg_op = 'INSERT'
                or new.seri_id is distinct from old.seri_id
                or old.status = 'ditolak'
                or new.kotak is null
                or new.kotak is distinct from old.kotak);
  if v_cek then
    select * into v_seri from public.lomba_seri where id = new.seri_id for update;
  else
    select * into v_seri from public.lomba_seri where id = new.seri_id;
  end if;
  if not found then
    raise exception 'SERI_TIDAK_VALID';
  end if;
  new.event_id := v_seri.event_id;
  if v_seri.jenis <> new.jenis then
    raise exception 'SERI_TIDAK_SESUAI_JENIS';
  end if;
  if new.harga is null then
    select j.harga into new.harga from public.lomba_jenis j where j.event_id = new.event_id and j.kode = new.jenis;
  end if;
  if v_cek then
    select count(*) into v_terisi
    from public.lomba_pendaftaran
    where seri_id = new.seri_id
      and status in ('menunggu', 'terkonfirmasi')
      and id <> new.id;
    if (tg_op = 'INSERT' or new.seri_id is distinct from old.seri_id or old.status = 'ditolak')
       and v_terisi >= v_seri.kuota then
      raise exception 'KUOTA_PENUH';
    end if;
  end if;

  -- 3b) posisi kotak di tabel jadwal (hanya grup jadwal terbang)
  if new.status not in ('menunggu', 'terkonfirmasi') or v_seri.sesi_id is null then
    new.kotak := null;
  elsif v_cek then
    if new.kotak is not null and (
         new.kotak < 1 or new.kotak > v_seri.kotak
         or new.kotak = any(v_seri.tutup)
         or exists (select 1 from public.lomba_pendaftaran p
                     where p.seri_id = new.seri_id and p.kotak = new.kotak
                       and p.status in ('menunggu', 'terkonfirmasi') and p.id <> new.id)) then
      new.kotak := null;
    end if;
    if new.kotak is null then
      select min(k) into v_k
        from generate_series(1, v_seri.kotak) k
       where not (k = any(v_seri.tutup))
         and not exists (select 1 from public.lomba_pendaftaran p
                          where p.seri_id = new.seri_id and p.kotak = k
                            and p.status in ('menunggu', 'terkonfirmasi') and p.id <> new.id);
      if v_k is null then
        raise exception 'KUOTA_PENUH';
      end if;
      new.kotak := v_k;
    end if;
  end if;

  -- 4) nomor layangan: unik per jenis di event yang sama (angka → tanpa nol di depan)
  if new.nomor_layangan is not null then
    new.nomor_layangan := nullif(upper(btrim(new.nomor_layangan)), '');
    if new.nomor_layangan ~ '^[0-9]+$' then
      new.nomor_layangan := coalesce(nullif(ltrim(new.nomor_layangan, '0'), ''), '0');
    end if;
  end if;
  if tg_op = 'INSERT' or new.nomor_layangan is distinct from old.nomor_layangan then
    new.nomor_urut := nullif(left(regexp_replace(coalesce(new.nomor_layangan, ''), '\D', '', 'g'), 9), '')::int;
  end if;
  if new.nomor_layangan is not null and new.status in ('menunggu', 'terkonfirmasi')
     and exists (select 1 from public.lomba_pendaftaran p
                  where p.event_id = new.event_id and p.jenis = new.jenis and p.nomor_layangan = new.nomor_layangan
                    and p.status in ('menunggu', 'terkonfirmasi') and p.id <> new.id) then
    raise exception 'NOMOR_DIPAKAI';
  end if;

  -- 5) jejak waktu & alasan
  if new.status = 'terkonfirmasi' then
    if tg_op = 'INSERT' or old.status is distinct from 'terkonfirmasi' then
      new.dikonfirmasi_at := now();
    end if;
  else
    new.dikonfirmasi_at := null;
  end if;
  if new.status <> 'ditolak' then
    new.alasan_tolak := null;
  end if;

  -- 6) data penting berubah → WA perlu dikirim ulang
  if tg_op = 'UPDATE'
     and new.wa_terkirim_at is not distinct from old.wa_terkirim_at
     and (new.status is distinct from old.status
          or new.seri_id is distinct from old.seri_id
          or new.jenis is distinct from old.jenis
          or new.nomor_layangan is distinct from old.nomor_layangan
          or new.kotak is distinct from old.kotak
          or new.no_wa is distinct from old.no_wa) then
    new.wa_terkirim_at := null;
  end if;

  new.updated_at := now();
  return new;
end;
$$;


-- ---------------------------------------------------------------------
-- BAGIAN 5 · FUNGSI PUBLIK (halaman depan & halaman peserta)
--   p_event kosong → event pertama (agar halaman versi lama tetap jalan)
-- ---------------------------------------------------------------------
create or replace function public.lomba_ev(p_event bigint)
returns bigint
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(p_event, public.lomba_event_default());
$$;

-- event dari kode alamat (#e/<kode>) — juga untuk event yang disembunyikan
create or replace function public.lomba_event_slug(p_slug text)
returns json
language sql
stable
security definer
set search_path = public
as $$
  select json_build_object('id', e.id, 'slug', e.slug, 'tampil', e.tampil)
    from public.lomba_event e where e.slug = lower(btrim(coalesce(p_slug, '')));
$$;

create or replace function public.lomba_info_situs()
returns json
language sql
stable
security definer
set search_path = public
as $$
  select json_build_object('nama', nama, 'judul', judul, 'teks', teks, 'logo_url', logo_url, 'bg_url', bg_url)
    from public.lomba_situs where id = 1;
$$;

-- ringkasan event (dipakai halaman depan & ruang panitia)
create or replace function public.lomba_ringkas_event(p_event bigint, p_admin boolean default false)
returns json
language sql
stable
security definer
set search_path = public
as $$
  with e as (select * from public.lomba_event where id = p_event),
       st as (select * from public.lomba_pengaturan where event_id = p_event),
       aktif as (select seri_id, count(*) as n from public.lomba_pendaftaran
                  where event_id = p_event and status in ('menunggu', 'terkonfirmasi') group by seri_id),
       grup as (select g.* from public.lomba_seri g where g.event_id = p_event and g.sesi_id is not null and g.aktif)
  select json_build_object(
    'id', e.id, 'slug', e.slug, 'tampil', e.tampil,
    'nama_event', st.nama_event, 'penyelenggara', st.penyelenggara, 'lokasi', st.lokasi,
    'logo_url', st.logo_url, 'bg_url', st.bg_url, 'flyer_url', st.flyer_url,
    'tanggal_mulai', st.tanggal_mulai, 'tanggal_selesai', coalesce(st.tanggal_selesai, st.tanggal_mulai),
    'pendaftaran_buka', coalesce(st.pendaftaran_buka and (st.batas_daftar is null or now() <= st.batas_daftar), false),
    'ada_jadwal', exists (select 1 from grup),
    'sisa_slot', coalesce((select sum(greatest(0, g.kuota - coalesce(a.n, 0))) from grup g left join aktif a on a.seri_id = g.id), 0),
    'jumlah_jenis', (select count(*) from public.lomba_jenis j where j.event_id = p_event and j.aktif),
    'harga_min', (select min(j.harga) from public.lomba_jenis j where j.event_id = p_event and j.aktif),
    'peserta', (select count(*) from public.lomba_pendaftaran p where p.event_id = p_event and p.status = 'terkonfirmasi'),
    'menunggu', case when p_admin then (select count(*) from public.lomba_pendaftaran p where p.event_id = p_event and p.status = 'menunggu') end,
    'pemasukan', case when p_admin then (select coalesce(sum(p.harga), 0) from public.lomba_pendaftaran p where p.event_id = p_event and p.status = 'terkonfirmasi') end,
    'panitia', case when p_admin and public.lomba_is_super()
                    then coalesce((select json_agg(ea.email order by ea.email) from public.lomba_event_admin ea where ea.event_id = p_event), '[]'::json) end)
  from e left join st on true;
$$;

-- halaman depan: semua event yang ditampilkan
create or replace function public.lomba_daftar_event()
returns json
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(json_agg(public.lomba_ringkas_event(e.id, false) order by e.id), '[]'::json)
    from public.lomba_event e where e.tampil;
$$;

-- info event, harga, jadwal + sisa kuota (tanpa data pribadi peserta)
drop function if exists public.lomba_info_publik();
create or replace function public.lomba_info_publik(p_event bigint default null)
returns json
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_ev bigint := public.lomba_ev(p_event);
  v_st public.lomba_pengaturan%rowtype;
begin
  select * into v_st from public.lomba_pengaturan where event_id = v_ev;
  if not found then
    return null;
  end if;
  return json_build_object(
    'event', json_build_object(
        'id', v_ev,
        'slug', (select slug from public.lomba_event where id = v_ev),
        'nama_event', v_st.nama_event, 'penyelenggara', v_st.penyelenggara, 'lokasi', v_st.lokasi,
        'info', v_st.info, 'wa_admin', v_st.wa_admin,
        'bank_nama', v_st.bank_nama, 'bank_no_rek', v_st.bank_no_rek, 'bank_atas_nama', v_st.bank_atas_nama,
        'pendaftaran_buka', v_st.pendaftaran_buka and (v_st.batas_daftar is null or now() <= v_st.batas_daftar),
        'batas_daftar', v_st.batas_daftar, 'tampilkan_peserta', v_st.tampilkan_peserta,
        'logo_url', v_st.logo_url, 'bg_url', v_st.bg_url, 'flyer_url', v_st.flyer_url,
        'tanggal_mulai', v_st.tanggal_mulai, 'tanggal_selesai', v_st.tanggal_selesai),
    'hari', coalesce((
      select json_agg(json_build_object('id', h.id, 'nama', h.nama, 'tanggal', h.tanggal, 'urutan', h.urutan)
             order by h.tanggal nulls last, h.urutan, h.id)
      from public.lomba_hari h where h.event_id = v_ev), '[]'::json),
    'sesi', coalesce((
      select json_agg(json_build_object('id', s.id, 'hari_id', s.hari_id, 'nama', s.nama,
                                        'jam_mulai', s.jam_mulai, 'jam_selesai', s.jam_selesai, 'urutan', s.urutan)
             order by s.jam_mulai nulls last, s.urutan, s.id)
      from public.lomba_sesi s where s.event_id = v_ev), '[]'::json),
    'jenis', coalesce((
      select json_agg(json_build_object('kode', j.kode, 'nama', j.nama, 'harga', j.harga, 'prefix', j.prefix, 'aktif', j.aktif)
             order by j.urutan, j.nama)
      from public.lomba_jenis j where j.event_id = v_ev), '[]'::json),
    'seri', coalesce((
      select json_agg(json_build_object(
               'id', s.id, 'jenis', s.jenis, 'nama', s.nama, 'tanggal', s.tanggal,
               'jam_mulai', s.jam_mulai, 'jam_selesai', s.jam_selesai,
               'kuota', s.kuota, 'aktif', s.aktif, 'catatan', s.catatan,
               'sesi_id', s.sesi_id, 'huruf', s.huruf, 'kotak', s.kotak, 'tutup', s.tutup,
               'terisi', (select count(*) from public.lomba_pendaftaran p
                           where p.seri_id = s.id and p.status in ('menunggu', 'terkonfirmasi')),
               'isi', (select coalesce(json_agg(json_build_object('kotak', p.kotak, 'status', p.status,
                                                                  'nomor', case when p.status = 'terkonfirmasi' then p.nomor_layangan end)
                                                order by p.kotak), '[]'::json)
                         from public.lomba_pendaftaran p
                        where p.seri_id = s.id and p.kotak is not null and p.status in ('menunggu', 'terkonfirmasi')),
               'peserta', case when v_st.tampilkan_peserta then (
                   select coalesce(json_agg(json_build_object('kotak', p.kotak, 'nomor', p.nomor_layangan,
                                                              'sekha', p.nama_sekha, 'alamat', p.alamat)
                                            order by p.kotak), '[]'::json)
                   from public.lomba_pendaftaran p
                   where p.seri_id = s.id and p.kotak is not null and p.status = 'terkonfirmasi') end)
             order by s.tanggal nulls last, s.jam_mulai nulls last, s.urutan, s.id)
      from public.lomba_seri s where s.event_id = v_ev), '[]'::json),
    'waktu_server', now());
end;
$$;

-- Simpan pendaftaran baru (status selalu "menunggu" verifikasi)
drop function if exists public.lomba_daftar(text, bigint, text, text, text, text, text, text, uuid, integer, text);
create or replace function public.lomba_daftar(
  p_jenis          text,
  p_seri_id        bigint,
  p_nama_sekha     text,
  p_alamat         text,
  p_no_wa          text,
  p_nama_rekening  text,
  p_bukti_path     text,
  p_bukti_hash     text default null,
  p_client_ref     uuid default null,
  p_harga          integer default null,
  p_nomor_layangan text default null,
  p_event          bigint default null
)
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
  v_ev     bigint := public.lomba_ev(p_event);
  v_set    public.lomba_pengaturan%rowtype;
  v_jenis  public.lomba_jenis%rowtype;
  v_seri   public.lomba_seri%rowtype;
  v_row    public.lomba_pendaftaran%rowtype;
  v_wa     text;
  v_ip     text;
  v_iphash text;
  v_ada    boolean;
  v_nomor  text;
  v_con    text;
begin
  -- kirim ulang (mis. koneksi putus) → kembalikan pendaftaran yang sama, tidak dobel
  if p_client_ref is not null then
    select * into v_row from public.lomba_pendaftaran where client_ref = p_client_ref;
    if found then
      return json_build_object('kode', v_row.kode, 'status', v_row.status, 'harga', v_row.harga,
                               'created_at', v_row.created_at, 'no_wa', v_row.no_wa,
                               'jenis', v_row.jenis, 'seri_id', v_row.seri_id, 'nama_sekha', v_row.nama_sekha,
                               'nomor_layangan', v_row.nomor_layangan, 'kotak', v_row.kotak);
    end if;
  end if;

  select * into v_set from public.lomba_pengaturan where event_id = v_ev;
  if not found or not v_set.pendaftaran_buka
     or (v_set.batas_daftar is not null and now() > v_set.batas_daftar) then
    raise exception 'PENDAFTARAN_DITUTUP';
  end if;

  select * into v_jenis from public.lomba_jenis where event_id = v_ev and kode = p_jenis;
  if not found or not v_jenis.aktif then
    raise exception 'JENIS_TIDAK_VALID';
  end if;
  if p_harga is not null and p_harga <> v_jenis.harga then
    raise exception 'HARGA_BERUBAH';
  end if;

  select * into v_seri from public.lomba_seri where id = p_seri_id and event_id = v_ev;
  if not found or v_seri.jenis <> p_jenis or not v_seri.aktif or v_seri.sesi_id is null then
    raise exception 'SERI_TIDAK_VALID';
  end if;

  v_nomor := btrim(coalesce(p_nomor_layangan, ''));
  if v_nomor !~ '^[0-9]{1,6}$' then
    raise exception 'NOMOR_TIDAK_VALID';
  end if;
  v_nomor := coalesce(nullif(ltrim(v_nomor, '0'), ''), '0');
  if exists (select 1 from public.lomba_pendaftaran
              where event_id = v_ev and jenis = p_jenis and nomor_layangan = v_nomor
                and status in ('menunggu', 'terkonfirmasi')) then
    raise exception 'NOMOR_DIPAKAI';
  end if;

  if char_length(btrim(coalesce(p_nama_sekha, ''))) not between 2 and 120
     or char_length(btrim(coalesce(p_alamat, ''))) not between 3 and 300
     or char_length(btrim(coalesce(p_nama_rekening, ''))) not between 2 and 120 then
    raise exception 'DATA_TIDAK_LENGKAP';
  end if;

  v_wa := public.lomba_normalisasi_wa(p_no_wa);
  if v_wa is null then
    raise exception 'WA_TIDAK_VALID';
  end if;

  if p_bukti_path is null
     or p_bukti_path !~ '^bukti/[0-9a-f-]{36}\.(jpg|jpeg|png|webp|pdf)$' then
    raise exception 'BUKTI_TIDAK_VALID';
  end if;
  begin
    select exists (select 1 from storage.objects
                   where bucket_id = 'lomba-bukti' and name = p_bukti_path) into v_ada;
  exception when others then
    v_ada := true;
  end;
  if not v_ada then
    raise exception 'BUKTI_TIDAK_VALID';
  end if;

  -- rem anti-spam: maks 15 per nomor WA per jam, 30 per jaringan per 10 menit
  if (select count(*) from public.lomba_pendaftaran
      where no_wa = v_wa and created_at > now() - interval '1 hour') >= 15 then
    raise exception 'TERLALU_BANYAK';
  end if;
  begin
    v_ip := nullif(btrim(split_part(coalesce(
              current_setting('request.headers', true)::json ->> 'cf-connecting-ip',
              current_setting('request.headers', true)::json ->> 'x-forwarded-for',
              current_setting('request.headers', true)::json ->> 'x-real-ip', ''), ',', 1)), '');
  exception when others then
    v_ip := null;
  end;
  if v_ip is not null then
    v_iphash := left(encode(sha256(convert_to('lomba:' || v_ip, 'UTF8')), 'hex'), 16);
    if (select count(*) from public.lomba_pendaftaran
        where ip_hash = v_iphash and created_at > now() - interval '10 minutes') >= 30 then
      raise exception 'TERLALU_BANYAK';
    end if;
  end if;

  insert into public.lomba_pendaftaran
    (event_id, client_ref, jenis, seri_id, nama_sekha, alamat, no_wa, nama_rekening,
     bukti_path, bukti_hash, harga, status, ip_hash, nomor_layangan)
  values
    (v_ev, p_client_ref, p_jenis, p_seri_id, p_nama_sekha, p_alamat, v_wa, p_nama_rekening,
     p_bukti_path, left(p_bukti_hash, 128), v_jenis.harga, 'menunggu', v_iphash, v_nomor)
  returning * into v_row;

  return json_build_object('kode', v_row.kode, 'status', v_row.status, 'harga', v_row.harga,
                           'created_at', v_row.created_at, 'no_wa', v_row.no_wa,
                           'jenis', v_row.jenis, 'seri_id', v_row.seri_id, 'nama_sekha', v_row.nama_sekha,
                           'nomor_layangan', v_row.nomor_layangan, 'kotak', v_row.kotak);
exception
  when unique_violation then
    get stacked diagnostics v_con = constraint_name;
    if p_client_ref is not null then
      select * into v_row from public.lomba_pendaftaran where client_ref = p_client_ref;
      if found then
        return json_build_object('kode', v_row.kode, 'status', v_row.status, 'harga', v_row.harga,
                                 'created_at', v_row.created_at, 'no_wa', v_row.no_wa,
                                 'jenis', v_row.jenis, 'seri_id', v_row.seri_id, 'nama_sekha', v_row.nama_sekha,
                                 'nomor_layangan', v_row.nomor_layangan, 'kotak', v_row.kotak);
      end if;
    end if;
    if coalesce(v_con, '') like '%nomor%' then
      raise exception 'NOMOR_DIPAKAI';
    end if;
    if coalesce(v_con, '') like '%kotak%' then
      raise exception 'KUOTA_PENUH';
    end if;
    raise exception 'BUKTI_TIDAK_VALID';
end;
$$;

drop function if exists public.lomba_cek_nomor(text, text);
create or replace function public.lomba_cek_nomor(p_jenis text, p_nomor text, p_event bigint default null)
returns boolean
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v text := btrim(coalesce(p_nomor, ''));
begin
  if v !~ '^[0-9]{1,6}$' then
    return false;
  end if;
  v := coalesce(nullif(ltrim(v, '0'), ''), '0');
  return not exists (select 1 from public.lomba_pendaftaran
                      where event_id = public.lomba_ev(p_event) and jenis = p_jenis and nomor_layangan = v
                        and status in ('menunggu', 'terkonfirmasi'));
end;
$$;

-- Data PDF konfirmasi (#tiket/KODE). Kode unik di semua event, jadi link lama tetap jalan.
create or replace function public.lomba_tiket(p_kode text)
returns json
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_kode text := upper(btrim(coalesce(p_kode, '')));
begin
  if v_kode !~ '^LL-[0-9A-Z]{6}$' then
    return null;
  end if;
  return (
    select json_build_object(
      'event', (select json_build_object('nama_event', st.nama_event, 'penyelenggara', st.penyelenggara,
                                         'lokasi', st.lokasi, 'logo_url', st.logo_url, 'bg_url', st.bg_url)
                  from public.lomba_pengaturan st where st.event_id = p.event_id),
      'event_slug', (select e.slug from public.lomba_event e where e.id = p.event_id),
      'kode', p.kode, 'nomor_layangan', p.nomor_layangan, 'jenis', j.nama,
      'nama_sekha', p.nama_sekha, 'alamat', p.alamat,
      'no_wa', p.no_wa,
      'kotak', p.kotak, 'seri_nama', s.nama, 'huruf', s.huruf, 'sesi_nama', ss.nama, 'hari', h.nama,
      'tanggal', s.tanggal, 'jam_mulai', s.jam_mulai, 'jam_selesai', s.jam_selesai)
    from public.lomba_pendaftaran p
    join public.lomba_jenis j on j.event_id = p.event_id and j.kode = p.jenis
    join public.lomba_seri s on s.id = p.seri_id
    left join public.lomba_sesi ss on ss.id = s.sesi_id
    left join public.lomba_hari h on h.id = ss.hari_id
    where p.kode = v_kode and p.status = 'terkonfirmasi'
  );
end;
$$;

-- kode event pemilik sebuah kode pendaftaran (link konfirmasi lama)
create or replace function public.lomba_event_dari_kode(p_kode text)
returns text
language sql
stable
security definer
set search_path = public
as $$
  select e.slug from public.lomba_pendaftaran p join public.lomba_event e on e.id = p.event_id
   where p.kode = upper(btrim(coalesce(p_kode, '')));
$$;

drop function if exists public.lomba_cek_status(text);
create or replace function public.lomba_cek_status(p_no_wa text, p_event bigint default null)
returns json
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_wa text := public.lomba_normalisasi_wa(p_no_wa);
  v_ev bigint := public.lomba_ev(p_event);
begin
  if v_wa is null then
    raise exception 'WA_TIDAK_VALID';
  end if;
  return coalesce((
    select json_agg(x order by x.created_at desc)
    from (
      select p.kode, p.jenis, j.nama as jenis_nama, p.nama_sekha, p.status,
             p.nomor_layangan, p.kotak, p.alasan_tolak, p.harga, p.created_at,
             s.nama as seri_nama, s.tanggal, s.jam_mulai, s.jam_selesai
      from public.lomba_pendaftaran p
      join public.lomba_jenis j on j.event_id = p.event_id and j.kode = p.jenis
      join public.lomba_seri s on s.id = p.seri_id
      where p.no_wa = v_wa and p.event_id = v_ev
      order by p.created_at desc
      limit 50
    ) x
  ), '[]'::json);
end;
$$;


-- ---------------------------------------------------------------------
-- BAGIAN 6 · FUNGSI ADMIN EVENT
-- ---------------------------------------------------------------------
create or replace function public.lomba_cek_setup()
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
  v_bucket boolean;
  v_media  boolean;
  v_pol    int;
  v_rt     boolean;
  v_admin  int;
begin
  if not public.lomba_is_admin() then
    raise exception 'BUKAN_ADMIN';
  end if;
  begin
    select exists (select 1 from storage.buckets where id = 'lomba-bukti') into v_bucket;
  exception when others then v_bucket := null;
  end;
  begin
    select exists (select 1 from storage.buckets where id = 'lomba-media') into v_media;
  exception when others then v_media := null;
  end;
  select count(*) into v_pol from pg_policies
   where schemaname = 'storage' and tablename = 'objects' and policyname like 'lomba_bukti_%';
  select exists (select 1 from pg_publication_tables
                  where pubname = 'supabase_realtime' and schemaname = 'public'
                    and tablename = 'lomba_pendaftaran') into v_rt;
  select count(*) into v_admin from public.lomba_admin;
  return json_build_object('bucket', v_bucket, 'media', v_media, 'storage_policies', v_pol,
                           'realtime', v_rt, 'admins', v_admin, 'versi', '3.0');
end;
$$;

create or replace function public.lomba_atur_kotak(p_seri_id bigint, p_kotak int, p_tutup boolean)
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
  v public.lomba_seri%rowtype;
begin
  select * into v from public.lomba_seri where id = p_seri_id;
  if not found or not public.lomba_boleh_event(v.event_id) then
    raise exception 'BUKAN_ADMIN';
  end if;
  update public.lomba_seri
     set tutup = case when p_tutup then array_append(array_remove(tutup, p_kotak), p_kotak)
                      else array_remove(tutup, p_kotak) end
   where id = p_seri_id
  returning * into v;
  return row_to_json(v);
end;
$$;

-- Hapus semua pendaftaran SATU event (setelah uji coba)
drop function if exists public.lomba_reset_data();
create or replace function public.lomba_reset_data(p_event bigint default null)
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
  v_ev    bigint := public.lomba_ev(p_event);
  v_paths json;
  v_n     int;
begin
  if not public.lomba_boleh_event(v_ev) then
    raise exception 'BUKAN_ADMIN';
  end if;
  select coalesce(json_agg(bukti_path), '[]'::json) into v_paths
    from public.lomba_pendaftaran where event_id = v_ev and bukti_path is not null;
  delete from public.lomba_pendaftaran where event_id = v_ev;
  get diagnostics v_n = row_count;
  update public.lomba_jenis set nomor_terakhir = 0 where event_id = v_ev;
  return json_build_object('dihapus', v_n, 'bukti_paths', v_paths);
end;
$$;


-- ---------------------------------------------------------------------
-- BAGIAN 7 · RUANG PANITIA & SUPER ADMIN
-- ---------------------------------------------------------------------
-- event yang boleh dibuka akun ini (super admin: semua)
create or replace function public.lomba_event_saya()
returns json
language plpgsql
stable
security definer
set search_path = public
as $$
begin
  if public.lomba_email_saya() is null then
    raise exception 'BELUM_MASUK';
  end if;
  return coalesce((select json_agg(public.lomba_ringkas_event(e.id, true) order by e.id)
                     from public.lomba_event e where public.lomba_boleh_event(e.id)), '[]'::json);
end;
$$;

create or replace function public.lomba_wajib_super()
returns void
language plpgsql
stable
security definer
set search_path = public
as $$
begin
  if not public.lomba_is_super() then
    raise exception 'BUKAN_SUPER_ADMIN';
  end if;
end;
$$;

create or replace function public.lomba_cek_slug(p_slug text, p_kecuali bigint default null)
returns text
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v text := lower(btrim(coalesce(p_slug, '')));
begin
  if v !~ '^[a-z0-9][a-z0-9-]{1,38}[a-z0-9]$' then
    raise exception 'KODE_EVENT_TIDAK_VALID';
  end if;
  if v in ('admin', 'panitia', 'semua', 'tiket')
     or exists (select 1 from public.lomba_event where slug = v and id is distinct from p_kecuali) then
    raise exception 'KODE_EVENT_DIPAKAI';
  end if;
  return v;
end;
$$;

create or replace function public.lomba_rapikan_email(p_email text)
returns text
language plpgsql
immutable
set search_path = public
as $$
declare
  v text := lower(btrim(coalesce(p_email, '')));
begin
  if v !~ '^[^@\s]+@[^@\s]+\.[^@\s]+$' then
    raise exception 'EMAIL_TIDAK_VALID';
  end if;
  return v;
end;
$$;

-- buat event baru (opsional: salin jenis, rekening, pesan, tampilan dari event lain)
create or replace function public.lomba_buat_event(p jsonb)
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
  v_slug  text;
  v_id    bigint;
  v_src   bigint := nullif(p ->> 'salin_dari', '')::bigint;
  v_salin jsonb := coalesce(p -> 'salin', '{}'::jsonb);
  v_a     public.lomba_pengaturan%rowtype;
  v_email text;
  v_mulai date := nullif(p ->> 'tanggal_mulai', '')::date;
  v_akhir date := coalesce(nullif(p ->> 'tanggal_selesai', '')::date, nullif(p ->> 'tanggal_mulai', '')::date);
begin
  perform public.lomba_wajib_super();
  if btrim(coalesce(p ->> 'nama_event', '')) = '' then
    raise exception 'DATA_TIDAK_LENGKAP';
  end if;
  if v_mulai is not null and v_akhir < v_mulai then
    raise exception 'TANGGAL_TIDAK_VALID';
  end if;
  v_slug := public.lomba_cek_slug(p ->> 'slug');
  insert into public.lomba_event (slug, tampil) values (v_slug, coalesce((p ->> 'tampil')::boolean, true))
  returning id into v_id;

  if v_src is not null then
    select * into v_a from public.lomba_pengaturan where event_id = v_src;
  end if;
  insert into public.lomba_pengaturan
    (event_id, nama_event, penyelenggara, lokasi, tanggal_mulai, tanggal_selesai, pendaftaran_buka,
     info, wa_admin, bank_nama, bank_no_rek, bank_atas_nama, template_wa_konfirmasi, template_wa_tolak, logo_url, bg_url, flyer_url)
  values
    (v_id, btrim(p ->> 'nama_event'),
     coalesce(nullif(btrim(p ->> 'penyelenggara'), ''), 'Panitia Lomba Layangan'),
     coalesce(btrim(p ->> 'lokasi'), ''), v_mulai, v_akhir, false,
     case when (v_salin ->> 'pesan')::boolean then coalesce(v_a.info, '') else '' end,
     case when (v_salin ->> 'pesan')::boolean then coalesce(v_a.wa_admin, '') else '' end,
     case when (v_salin ->> 'bank')::boolean then coalesce(v_a.bank_nama, '') else '' end,
     case when (v_salin ->> 'bank')::boolean then coalesce(v_a.bank_no_rek, '') else '' end,
     case when (v_salin ->> 'bank')::boolean then coalesce(v_a.bank_atas_nama, '') else '' end,
     case when (v_salin ->> 'pesan')::boolean then coalesce(v_a.template_wa_konfirmasi, '') else '' end,
     case when (v_salin ->> 'pesan')::boolean then coalesce(v_a.template_wa_tolak, '') else '' end,
     case when (v_salin ->> 'tampilan')::boolean then coalesce(v_a.logo_url, '') else '' end,
     case when (v_salin ->> 'tampilan')::boolean then coalesce(v_a.bg_url, '') else '' end,
     '');

  if v_src is not null and coalesce((v_salin ->> 'jenis')::boolean, false) then
    insert into public.lomba_jenis (event_id, kode, nama, harga, prefix, urutan, aktif, nomor_terakhir)
    select v_id, kode, nama, harga, prefix, urutan, aktif, 0 from public.lomba_jenis where event_id = v_src;
  end if;

  for v_email in select distinct public.lomba_rapikan_email(x) from jsonb_array_elements_text(coalesce(p -> 'panitia', '[]'::jsonb)) x
  loop
    insert into public.lomba_event_admin (event_id, email) values (v_id, v_email) on conflict do nothing;
  end loop;
  return public.lomba_ringkas_event(v_id, true);
end;
$$;

create or replace function public.lomba_ubah_event(p_id bigint, p_slug text default null, p_tampil boolean default null)
returns json
language plpgsql
security definer
set search_path = public
as $$
begin
  perform public.lomba_wajib_super();
  if not exists (select 1 from public.lomba_event where id = p_id) then
    raise exception 'EVENT_TIDAK_ADA';
  end if;
  update public.lomba_event
     set slug   = case when p_slug is null then slug else public.lomba_cek_slug(p_slug, p_id) end,
         tampil = coalesce(p_tampil, tampil)
   where id = p_id;
  return public.lomba_ringkas_event(p_id, true);
end;
$$;

-- hapus event beserta seluruh isinya; mengembalikan file bukti untuk dihapus dari Storage
create or replace function public.lomba_hapus_event(p_id bigint)
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
  v_paths json;
begin
  perform public.lomba_wajib_super();
  select coalesce(json_agg(bukti_path), '[]'::json) into v_paths
    from public.lomba_pendaftaran where event_id = p_id and bukti_path is not null;
  delete from public.lomba_pendaftaran where event_id = p_id;
  delete from public.lomba_seri        where event_id = p_id;
  delete from public.lomba_sesi        where event_id = p_id;
  delete from public.lomba_hari        where event_id = p_id;
  delete from public.lomba_jenis       where event_id = p_id;
  delete from public.lomba_pengaturan  where event_id = p_id;
  delete from public.lomba_event_admin where event_id = p_id;
  delete from public.lomba_event       where id = p_id;
  return json_build_object('bukti_paths', v_paths);
end;
$$;

-- akses admin event: tambah, ganti email, cabut
create or replace function public.lomba_tambah_akses(p_event bigint, p_email text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v text := public.lomba_rapikan_email(p_email);
begin
  perform public.lomba_wajib_super();
  if exists (select 1 from public.lomba_admin where lower(email) = v) then
    raise exception 'EMAIL_SUPER';
  end if;
  insert into public.lomba_event_admin (event_id, email) values (p_event, v);
exception when unique_violation then
  raise exception 'EMAIL_SUDAH_ADA';
end;
$$;

create or replace function public.lomba_ganti_akses(p_event bigint, p_lama text, p_baru text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v text := public.lomba_rapikan_email(p_baru);
begin
  perform public.lomba_wajib_super();
  if exists (select 1 from public.lomba_admin where lower(email) = v) then
    raise exception 'EMAIL_SUPER';
  end if;
  update public.lomba_event_admin set email = v where event_id = p_event and email = lower(btrim(p_lama));
  if not found then
    raise exception 'EVENT_TIDAK_ADA';
  end if;
exception when unique_violation then
  raise exception 'EMAIL_SUDAH_ADA';
end;
$$;

-- p_event kosong = cabut dari SEMUA event
create or replace function public.lomba_cabut_akses(p_event bigint, p_email text)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  perform public.lomba_wajib_super();
  delete from public.lomba_event_admin
   where email = lower(btrim(p_email)) and (p_event is null or event_id = p_event);
end;
$$;

-- ganti email satu orang di semua event yang dipegangnya
create or replace function public.lomba_ganti_email_panitia(p_lama text, p_baru text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_lama text := lower(btrim(p_lama));
  v      text := public.lomba_rapikan_email(p_baru);
begin
  perform public.lomba_wajib_super();
  if v = v_lama then
    return;
  end if;
  if exists (select 1 from public.lomba_admin where lower(email) = v) then
    raise exception 'EMAIL_SUPER';
  end if;
  delete from public.lomba_event_admin a
   where a.email = v_lama and exists (select 1 from public.lomba_event_admin b where b.event_id = a.event_id and b.email = v);
  update public.lomba_event_admin set email = v where email = v_lama;
end;
$$;

-- semua admin event & event yang dipegang (untuk super admin)
create or replace function public.lomba_daftar_akses()
returns json
language plpgsql
stable
security definer
set search_path = public
as $$
begin
  perform public.lomba_wajib_super();
  return coalesce((
    select json_agg(json_build_object('email', x.email, 'events', x.events) order by x.email)
    from (
      select ea.email, json_agg(json_build_object('id', e.id, 'slug', e.slug, 'nama_event', st.nama_event,
                                                  'tanggal_mulai', st.tanggal_mulai, 'tanggal_selesai', st.tanggal_selesai)
                                order by st.tanggal_mulai nulls last, e.id) as events
        from public.lomba_event_admin ea
        join public.lomba_event e on e.id = ea.event_id
        left join public.lomba_pengaturan st on st.event_id = e.id
       group by ea.email
    ) x), '[]'::json);
end;
$$;

create or replace function public.lomba_simpan_situs(p jsonb)
returns json
language plpgsql
security definer
set search_path = public
as $$
begin
  perform public.lomba_wajib_super();
  if p ? 'nama' and btrim(coalesce(p ->> 'nama', '')) = '' then
    raise exception 'DATA_TIDAK_LENGKAP';
  end if;
  update public.lomba_situs set
    nama     = case when p ? 'nama'     then btrim(p ->> 'nama')                   else nama end,
    judul    = case when p ? 'judul'    then btrim(coalesce(p ->> 'judul', ''))    else judul end,
    teks     = case when p ? 'teks'     then btrim(coalesce(p ->> 'teks', ''))     else teks end,
    logo_url = case when p ? 'logo_url' then btrim(coalesce(p ->> 'logo_url', '')) else logo_url end,
    bg_url   = case when p ? 'bg_url'   then btrim(coalesce(p ->> 'bg_url', ''))   else bg_url end,
    updated_at = now()
  where id = 1;
  return public.lomba_info_situs();
end;
$$;

-- semua file bukti yang masih dipakai (untuk membersihkan file yatim)
create or replace function public.lomba_bukti_terpakai()
returns json
language plpgsql
stable
security definer
set search_path = public
as $$
begin
  perform public.lomba_wajib_super();
  return coalesce((select json_agg(bukti_path) from public.lomba_pendaftaran where bukti_path is not null), '[]'::json);
end;
$$;


-- ---------------------------------------------------------------------
-- BAGIAN 8 · KEAMANAN (RLS): admin hanya melihat event yang ditugaskan
-- ---------------------------------------------------------------------
alter table public.lomba_event        enable row level security;
alter table public.lomba_event_admin  enable row level security;
alter table public.lomba_situs        enable row level security;

do $$
declare
  t text;
begin
  foreach t in array array['lomba_jenis', 'lomba_hari', 'lomba_sesi', 'lomba_seri', 'lomba_pendaftaran']
  loop
    execute format('drop policy if exists lomba_admin_kelola on public.%I', t);
    execute format('create policy lomba_admin_kelola on public.%I for all to authenticated
                      using ((select public.lomba_boleh_event(event_id)))
                      with check ((select public.lomba_boleh_event(event_id)))', t);
  end loop;
end $$;

-- pengaturan event: admin event boleh membaca & mengubah; membuat/menghapus hanya lewat fungsi super admin
drop policy if exists lomba_admin_kelola on public.lomba_pengaturan;
drop policy if exists lomba_admin_baca on public.lomba_pengaturan;
drop policy if exists lomba_admin_ubah on public.lomba_pengaturan;
create policy lomba_admin_baca on public.lomba_pengaturan for select to authenticated
  using ((select public.lomba_boleh_event(event_id)));
create policy lomba_admin_ubah on public.lomba_pengaturan for update to authenticated
  using ((select public.lomba_boleh_event(event_id)))
  with check ((select public.lomba_boleh_event(event_id)));

drop policy if exists lomba_event_baca on public.lomba_event;
create policy lomba_event_baca on public.lomba_event for select to authenticated
  using ((select public.lomba_boleh_event(id)));

drop policy if exists lomba_event_admin_baca on public.lomba_event_admin;
create policy lomba_event_admin_baca on public.lomba_event_admin for select to authenticated
  using ((select public.lomba_is_super()) or email = (select public.lomba_email_saya()));


-- ---------------------------------------------------------------------
-- BAGIAN 9 · HAK AKSES (GRANT)
-- ---------------------------------------------------------------------
revoke all on table public.lomba_event, public.lomba_event_admin, public.lomba_situs from anon;
revoke all on table public.lomba_event_admin, public.lomba_situs from authenticated;
grant select on table public.lomba_event, public.lomba_event_admin to authenticated;
revoke insert, delete on table public.lomba_pengaturan from authenticated;
grant select, update on table public.lomba_pengaturan to authenticated;
grant select, insert, update, delete on table public.lomba_event, public.lomba_event_admin, public.lomba_situs to service_role;

revoke all on function public.lomba_trg_event_tetap() from public, anon, authenticated;
revoke all on function public.lomba_trg_pengaturan() from public, anon, authenticated;
revoke all on function public.lomba_trg_pendaftaran() from public, anon, authenticated;
revoke all on function public.lomba_trg_seri() from public, anon, authenticated;
revoke all on function public.lomba_trg_sesi_sinkron() from public, anon, authenticated;
revoke all on function public.lomba_buat_event(jsonb) from public, anon;
revoke all on function public.lomba_ubah_event(bigint, text, boolean) from public, anon;
revoke all on function public.lomba_hapus_event(bigint) from public, anon;
revoke all on function public.lomba_tambah_akses(bigint, text) from public, anon;
revoke all on function public.lomba_ganti_akses(bigint, text, text) from public, anon;
revoke all on function public.lomba_cabut_akses(bigint, text) from public, anon;
revoke all on function public.lomba_ganti_email_panitia(text, text) from public, anon;
revoke all on function public.lomba_daftar_akses() from public, anon;
revoke all on function public.lomba_simpan_situs(jsonb) from public, anon;
revoke all on function public.lomba_bukti_terpakai() from public, anon;
revoke all on function public.lomba_event_saya() from public, anon;
revoke all on function public.lomba_reset_data(bigint) from public, anon;
revoke all on function public.lomba_cek_setup() from public, anon;
revoke all on function public.lomba_atur_kotak(bigint, int, boolean) from public, anon;
revoke all on function public.lomba_wajib_super() from public, anon;
revoke all on function public.lomba_ringkas_event(bigint, boolean) from public, anon, authenticated;

grant execute on function public.lomba_event_default() to anon, authenticated;
grant execute on function public.lomba_ev(bigint) to anon, authenticated;
grant execute on function public.lomba_event_slug(text) to anon, authenticated;
grant execute on function public.lomba_info_situs() to anon, authenticated;
grant execute on function public.lomba_daftar_event() to anon, authenticated;
grant execute on function public.lomba_info_publik(bigint) to anon, authenticated;
grant execute on function public.lomba_daftar(text, bigint, text, text, text, text, text, text, uuid, integer, text, bigint) to anon, authenticated;
grant execute on function public.lomba_cek_nomor(text, text, bigint) to anon, authenticated;
grant execute on function public.lomba_cek_status(text, bigint) to anon, authenticated;
grant execute on function public.lomba_tiket(text) to anon, authenticated;
grant execute on function public.lomba_event_dari_kode(text) to anon, authenticated;
grant execute on function public.lomba_is_admin() to anon, authenticated;
grant execute on function public.lomba_is_super() to anon, authenticated;
grant execute on function public.lomba_boleh_event(bigint) to anon, authenticated;
grant execute on function public.lomba_email_saya() to anon, authenticated;
grant execute on function public.lomba_peran() to anon, authenticated;
grant execute on function public.lomba_cek_slug(text, bigint) to authenticated;
grant execute on function public.lomba_rapikan_email(text) to authenticated;
grant execute on function public.lomba_wajib_super() to authenticated;
grant execute on function public.lomba_event_saya() to authenticated;
grant execute on function public.lomba_buat_event(jsonb) to authenticated;
grant execute on function public.lomba_ubah_event(bigint, text, boolean) to authenticated;
grant execute on function public.lomba_hapus_event(bigint) to authenticated;
grant execute on function public.lomba_tambah_akses(bigint, text) to authenticated;
grant execute on function public.lomba_ganti_akses(bigint, text, text) to authenticated;
grant execute on function public.lomba_cabut_akses(bigint, text) to authenticated;
grant execute on function public.lomba_ganti_email_panitia(text, text) to authenticated;
grant execute on function public.lomba_daftar_akses() to authenticated;
grant execute on function public.lomba_simpan_situs(jsonb) to authenticated;
grant execute on function public.lomba_bukti_terpakai() to authenticated;
grant execute on function public.lomba_reset_data(bigint) to authenticated;
grant execute on function public.lomba_cek_setup() to authenticated;
grant execute on function public.lomba_atur_kotak(bigint, int, boolean) to authenticated;


-- ---------------------------------------------------------------------
-- BAGIAN 10 · STORAGE: bukti transfer hanya bisa dibuka admin event-nya
-- ---------------------------------------------------------------------
do $$
begin
  drop policy if exists "lomba_bukti_admin_baca" on storage.objects;
  create policy "lomba_bukti_admin_baca" on storage.objects
    for select to authenticated
    using (bucket_id = 'lomba-bukti' and (
      (select public.lomba_is_super())
      or exists (select 1 from public.lomba_pendaftaran p
                  where p.bukti_path = storage.objects.name and public.lomba_boleh_event(p.event_id))));

  drop policy if exists "lomba_bukti_admin_hapus" on storage.objects;
  create policy "lomba_bukti_admin_hapus" on storage.objects
    for delete to authenticated
    using (bucket_id = 'lomba-bukti' and (
      (select public.lomba_is_super())
      or exists (select 1 from public.lomba_pendaftaran p
                  where p.bukti_path = storage.objects.name and public.lomba_boleh_event(p.event_id))));
exception when others then
  raise notice 'Policy storage tidak bisa diperbarui lewat SQL (%).', sqlerrm;
end;
$$;


-- ---------------------------------------------------------------------
-- BAGIAN 11 · CEK MULTI-EVENT — semua baris sebaiknya ✅
-- ---------------------------------------------------------------------
select no, cek, hasil from (values
  (1, 'Event pertama (data lama)',
      coalesce((select '✅ ' || e.slug || ' — ' || st.nama_event
                  from public.lomba_event e join public.lomba_pengaturan st on st.event_id = e.id
                 order by e.id limit 1), '❌ Belum ada')),
  (2, 'Semua data punya event',
      case when not exists (select 1 from public.lomba_pendaftaran where event_id is null)
            and not exists (select 1 from public.lomba_seri where event_id is null)
           then '✅ OK' else '❌ Ada data tanpa event' end),
  (3, 'Jumlah pendaftaran (harus sama dengan sebelum pembaruan)',
      '✅ ' || (select count(*) from public.lomba_pendaftaran)::text),
  (4, 'Super admin',
      coalesce((select '✅ ' || string_agg(email, ', ') from public.lomba_admin), '❌ Belum ada')),
  (5, 'Fungsi multi-event',
      case when to_regprocedure('public.lomba_daftar(text,bigint,text,text,text,text,text,text,uuid,integer,text,bigint)') is not null
            and to_regprocedure('public.lomba_buat_event(jsonb)') is not null
            and to_regprocedure('public.lomba_daftar_event()') is not null
           then '✅ OK' else '❌ Gagal' end),
  (6, 'Pengaturan situs (halaman depan)',
      case when exists (select 1 from public.lomba_situs where id = 1) then '✅ OK' else '❌ Belum ada' end)
) as t(no, cek, hasil)
order by no;
