-- =====================================================================
--  SISTEM PENDAFTARAN LOMBA LAYANGAN  ·  setup database Supabase
--  Versi 2.0 — Oktober 2026 (Jadwal Terbang: hari → seri → grup)
-- ---------------------------------------------------------------------
--  CARA PAKAI
--   1. Supabase Dashboard → SQL Editor → New query
--   2. Cek email admin di BAGIAN 10 (default: adeyudistira62@gmail.com)
--   3. Paste SELURUH isi file ini → klik Run
--   4. Lihat tabel "cek setup" di panel hasil: semua baris harus ✅
--
--  Aman dijalankan ulang: tabel dibuat hanya jika belum ada, fungsi &
--  policy diperbarui, data pendaftaran yang sudah ada TIDAK dihapus.
--  Semua objek memakai awalan "lomba_" supaya aman digabung dengan
--  project Supabase yang sudah ada (mis. project PMS).
-- =====================================================================


-- ---------------------------------------------------------------------
-- BAGIAN 1 · FUNGSI BANTU (dibuat sebelum tabel)
-- ---------------------------------------------------------------------

-- Nomor WA → format 62xxxxxxxxxx (08.. → 628.., 8.. → 628..). Null jika tidak valid.
create or replace function public.lomba_normalisasi_wa(p text)
returns text
language plpgsql
immutable
set search_path = public
as $$
declare
  d text := regexp_replace(coalesce(p, ''), '\D', '', 'g');
begin
  if d like '0%' then
    d := '62' || substr(d, 2);
  elsif d like '8%' then
    d := '62' || d;
  end if;
  if d like '620%' then
    d := '62' || substr(d, 4);   -- '+62 0812…' → '62812…'
  end if;
  if d ~ '^[1-9][0-9]{9,14}$' then
    return d;
  end if;
  return null;
end;
$$;

-- Kode pendaftaran acak & unik, contoh: LL-7K3Q9P (tanpa huruf/angka yang mirip)
create or replace function public.lomba_kode_baru()
returns text
language plpgsql
volatile
security definer
set search_path = public
as $$
declare
  abc constant text := '23456789ABCDEFGHJKLMNPQRSTUVWXYZ';
  v text;
begin
  loop
    v := 'LL-';
    for i in 1..6 loop
      v := v || substr(abc, 1 + floor(random() * 32)::int, 1);
    end loop;
    exit when not exists (select 1 from public.lomba_pendaftaran where kode = v);
  end loop;
  return v;
end;
$$;


-- ---------------------------------------------------------------------
-- BAGIAN 2 · TABEL
-- ---------------------------------------------------------------------

-- Daftar email yang boleh masuk dashboard admin
create table if not exists public.lomba_admin (
  email       text primary key,
  created_at  timestamptz not null default now()
);

-- Pengaturan event (hanya 1 baris, id = 1)
create table if not exists public.lomba_pengaturan (
  id                      int primary key default 1 check (id = 1),
  nama_event              text not null default 'Lomba Layangan Tradisional',
  penyelenggara           text not null default 'Panitia Lomba Layangan',
  lokasi                  text not null default '',
  info                    text not null default '',
  wa_admin                text not null default '',
  bank_nama               text not null default '',
  bank_no_rek             text not null default '',
  bank_atas_nama          text not null default '',
  pendaftaran_buka        boolean not null default true,
  batas_daftar            timestamptz,
  tampilkan_peserta       boolean not null default false,
  template_wa_konfirmasi  text not null default '',
  template_wa_tolak       text not null default '',
  updated_at              timestamptz not null default now()
);

-- Jenis layangan + harga + awalan nomor layangan
create table if not exists public.lomba_jenis (
  kode            text primary key,
  nama            text not null,
  harga           integer not null check (harga >= 0),
  prefix          text not null,
  urutan          int not null default 0,
  aktif           boolean not null default true,
  nomor_terakhir  int not null default 0 check (nomor_terakhir >= 0)
);

-- Seri = jadwal terbang, khusus per jenis layangan, kuota default 60
create table if not exists public.lomba_seri (
  id           bigint generated by default as identity primary key,
  jenis        text not null references public.lomba_jenis(kode) on update cascade,
  nama         text not null,
  tanggal      date,
  jam_mulai    time,
  jam_selesai  time,
  kuota        int not null default 60 check (kuota >= 0),
  aktif        boolean not null default true,
  catatan      text not null default '',
  urutan       int not null default 0,
  created_at   timestamptz not null default now()
);
create index if not exists lomba_seri_jenis_idx on public.lomba_seri (jenis);

-- ---------------------------------------------------------------------
-- JADWAL TERBANG (v2): Hari → Seri (blok waktu, mis. Seri I 09.30–10.30)
--                      → Grup A, B, C… (1 jenis layangan, mis. 50 kotak)
--   · Tabel lomba_seri di atas dipakai sebagai GRUP: 1 baris = 1 grup
--     (jenis + jumlah kotak + kotak yang ditutup panitia).
--   · Tanggal, jam, dan nama grup ("Seri I · A") diisi otomatis dari
--     hari & seri, jadi tampilan lama (WA, cek status, ekspor) tetap jalan.
--   · Grup tanpa sesi_id = seri lama (sebelum jadwal terbang).
-- ---------------------------------------------------------------------
create table if not exists public.lomba_hari (
  id          bigint generated by default as identity primary key,
  nama        text not null,
  tanggal     date,
  urutan      int not null default 0,
  created_at  timestamptz not null default now()
);

-- "Seri" pada tabel jadwal (I, II, III…) = blok waktu terbang dalam 1 hari
create table if not exists public.lomba_sesi (
  id           bigint generated by default as identity primary key,
  hari_id      bigint not null references public.lomba_hari(id) on delete restrict,
  nama         text not null,
  jam_mulai    time,
  jam_selesai  time,
  urutan       int not null default 0,
  created_at   timestamptz not null default now()
);
create index if not exists lomba_sesi_hari_idx on public.lomba_sesi (hari_id);

alter table public.lomba_seri add column if not exists sesi_id bigint references public.lomba_sesi(id) on delete restrict;
alter table public.lomba_seri add column if not exists huruf   text;
alter table public.lomba_seri add column if not exists kotak   int not null default 50;
alter table public.lomba_seri add column if not exists tutup   int[] not null default '{}';
do $$ begin
  alter table public.lomba_seri add constraint lomba_seri_kotak_chk check (kotak between 1 and 200);
exception when duplicate_object then null; end $$;
create index if not exists lomba_seri_sesi_idx on public.lomba_seri (sesi_id);
create unique index if not exists lomba_seri_sesi_huruf_uidx on public.lomba_seri (sesi_id, huruf) where sesi_id is not null;

-- Tampilan halaman peserta: logo & gambar latar (diatur admin di Pengaturan)
alter table public.lomba_pengaturan add column if not exists logo_url text not null default '';
alter table public.lomba_pengaturan add column if not exists bg_url   text not null default '';

-- Pendaftaran: 1 baris = 1 layangan
create table if not exists public.lomba_pendaftaran (
  id               uuid primary key default gen_random_uuid(),
  kode             text not null unique default public.lomba_kode_baru(),
  client_ref       uuid unique,
  jenis            text not null references public.lomba_jenis(kode) on update cascade,
  seri_id          bigint not null references public.lomba_seri(id),
  nama_sekha       text not null,
  alamat           text not null,
  no_wa            text not null,
  nama_rekening    text not null,
  bukti_path       text,
  bukti_hash       text,
  harga            integer not null,
  status           text not null default 'menunggu'
                   check (status in ('menunggu', 'terkonfirmasi', 'ditolak')),
  nomor_urut       int,
  nomor_layangan   text unique,
  alasan_tolak     text,
  catatan_admin    text not null default '',
  wa_terkirim_at   timestamptz,
  dikonfirmasi_at  timestamptz,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);
create index if not exists lomba_pendaftaran_seri_status_idx on public.lomba_pendaftaran (seri_id, status);
create index if not exists lomba_pendaftaran_wa_idx on public.lomba_pendaftaran (no_wa);
create index if not exists lomba_pendaftaran_created_idx on public.lomba_pendaftaran (created_at desc);
create index if not exists lomba_pendaftaran_hash_idx on public.lomba_pendaftaran (bukti_hash) where bukti_hash is not null;
create unique index if not exists lomba_pendaftaran_bukti_uidx on public.lomba_pendaftaran (bukti_path) where bukti_path is not null;
alter table public.lomba_pendaftaran add column if not exists ip_hash text;
create index if not exists lomba_pendaftaran_ip_idx on public.lomba_pendaftaran (ip_hash, created_at) where ip_hash is not null;

-- v2: posisi kotak di tabel jadwal (1 = kotak pertama grup), diisi otomatis
alter table public.lomba_pendaftaran add column if not exists kotak int;
create unique index if not exists lomba_pendaftaran_kotak_uidx on public.lomba_pendaftaran (seri_id, kotak)
  where kotak is not null and status in ('menunggu', 'terkonfirmasi');

-- v2: nomor layangan diisi peserta, unik PER JENIS (yang ditolak melepas nomornya)
alter table public.lomba_pendaftaran drop constraint if exists lomba_pendaftaran_nomor_layangan_key;
create unique index if not exists lomba_pendaftaran_nomor_uidx on public.lomba_pendaftaran (jenis, nomor_layangan)
  where nomor_layangan is not null and status in ('menunggu', 'terkonfirmasi');


-- ---------------------------------------------------------------------
-- BAGIAN 3 · CEK ADMIN
-- ---------------------------------------------------------------------
create or replace function public.lomba_is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.lomba_admin a
    join auth.users u on lower(u.email) = lower(a.email)
    where u.id = auth.uid()
      and u.email_confirmed_at is not null
  );
$$;


-- ---------------------------------------------------------------------
-- BAGIAN 4 · ATURAN OTOMATIS (TRIGGER)
--   · kuota seri dijaga di database (aman walau banyak yang daftar bersamaan)
--   · nomor layangan otomatis per jenis saat status → terkonfirmasi (BB-001, …)
--   · tanda "WA terkirim" direset bila data penting berubah
-- ---------------------------------------------------------------------
create or replace function public.lomba_trg_pendaftaran()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_seri    public.lomba_seri%rowtype;
  v_terisi  int;
  v_cek     boolean;
  v_k       int;
begin
  -- 1) rapikan & validasi data dasar
  new.nama_sekha    := btrim(coalesce(new.nama_sekha, ''));
  new.alamat        := btrim(coalesce(new.alamat, ''));
  new.nama_rekening := btrim(coalesce(new.nama_rekening, ''));
  new.no_wa         := public.lomba_normalisasi_wa(new.no_wa);
  if new.no_wa is null then
    raise exception 'WA_TIDAK_VALID';
  end if;
  if new.nama_sekha = '' or new.alamat = '' or new.nama_rekening = '' then
    raise exception 'DATA_TIDAK_LENGKAP';
  end if;

  -- 2) jenis diganti → harga mengikuti jenis baru
  if tg_op = 'UPDATE' and new.jenis is distinct from old.jenis then
    new.harga := null;
  end if;
  -- pindah grup → posisi kotak dipilih ulang
  if tg_op = 'UPDATE' and new.seri_id is distinct from old.seri_id
     and new.kotak is not distinct from old.kotak then
    new.kotak := null;
  end if;
  if new.harga is null then
    select j.harga into new.harga from public.lomba_jenis j where j.kode = new.jenis;
  end if;

  -- 3) seri harus sesuai jenis + cek kuota (baris seri dikunci agar antre)
  v_cek := new.status in ('menunggu', 'terkonfirmasi')
           and (tg_op = 'INSERT'
                or new.seri_id is distinct from old.seri_id
                or old.status = 'ditolak'
                or new.kotak is null
                or new.kotak is distinct from old.kotak);
  if v_cek then
    select * into v_seri from public.lomba_seri where id = new.seri_id for update;
  else
    select * into v_seri from public.lomba_seri where id = new.seri_id;
  end if;
  if not found then
    raise exception 'SERI_TIDAK_VALID';
  end if;
  if v_seri.jenis <> new.jenis then
    raise exception 'SERI_TIDAK_SESUAI_JENIS';
  end if;
  if v_cek then
    select count(*) into v_terisi
    from public.lomba_pendaftaran
    where seri_id = new.seri_id
      and status in ('menunggu', 'terkonfirmasi')
      and id <> new.id;
    if (tg_op = 'INSERT' or new.seri_id is distinct from old.seri_id or old.status = 'ditolak')
       and v_terisi >= v_seri.kuota then
      raise exception 'KUOTA_PENUH';
    end if;
  end if;

  -- 3b) posisi kotak di tabel jadwal (hanya grup jadwal terbang)
  if new.status not in ('menunggu', 'terkonfirmasi') or v_seri.sesi_id is null then
    new.kotak := null;
  elsif v_cek then
    if new.kotak is not null and (
         new.kotak < 1 or new.kotak > v_seri.kotak
         or new.kotak = any(v_seri.tutup)
         or exists (select 1 from public.lomba_pendaftaran p
                     where p.seri_id = new.seri_id and p.kotak = new.kotak
                       and p.status in ('menunggu', 'terkonfirmasi') and p.id <> new.id)) then
      new.kotak := null;
    end if;
    if new.kotak is null then
      select min(k) into v_k
        from generate_series(1, v_seri.kotak) k
       where not (k = any(v_seri.tutup))
         and not exists (select 1 from public.lomba_pendaftaran p
                          where p.seri_id = new.seri_id and p.kotak = k
                            and p.status in ('menunggu', 'terkonfirmasi') and p.id <> new.id);
      if v_k is null then
        raise exception 'KUOTA_PENUH';
      end if;
      new.kotak := v_k;
    end if;
  end if;

  -- 4) nomor layangan: diisi peserta, unik per jenis (angka → tanpa nol di depan)
  if new.nomor_layangan is not null then
    new.nomor_layangan := nullif(upper(btrim(new.nomor_layangan)), '');
    if new.nomor_layangan ~ '^[0-9]+$' then
      new.nomor_layangan := coalesce(nullif(ltrim(new.nomor_layangan, '0'), ''), '0');
    end if;
  end if;
  if tg_op = 'INSERT' or new.nomor_layangan is distinct from old.nomor_layangan then
    new.nomor_urut := nullif(left(regexp_replace(coalesce(new.nomor_layangan, ''), '\D', '', 'g'), 9), '')::int;
  end if;
  if new.nomor_layangan is not null and new.status in ('menunggu', 'terkonfirmasi')
     and exists (select 1 from public.lomba_pendaftaran p
                  where p.jenis = new.jenis and p.nomor_layangan = new.nomor_layangan
                    and p.status in ('menunggu', 'terkonfirmasi') and p.id <> new.id) then
    raise exception 'NOMOR_DIPAKAI';
  end if;

  -- 5) jejak waktu & alasan
  if new.status = 'terkonfirmasi' then
    if tg_op = 'INSERT' or old.status is distinct from 'terkonfirmasi' then
      new.dikonfirmasi_at := now();
    end if;
  else
    new.dikonfirmasi_at := null;
  end if;
  if new.status <> 'ditolak' then
    new.alasan_tolak := null;
  end if;

  -- 6) data penting berubah → WA perlu dikirim ulang
  if tg_op = 'UPDATE'
     and new.wa_terkirim_at is not distinct from old.wa_terkirim_at
     and (new.status is distinct from old.status
          or new.seri_id is distinct from old.seri_id
          or new.jenis is distinct from old.jenis
          or new.nomor_layangan is distinct from old.nomor_layangan
          or new.kotak is distinct from old.kotak
          or new.no_wa is distinct from old.no_wa) then
    new.wa_terkirim_at := null;
  end if;

  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists lomba_pendaftaran_biu on public.lomba_pendaftaran;
create trigger lomba_pendaftaran_biu
  before insert or update on public.lomba_pendaftaran
  for each row execute function public.lomba_trg_pendaftaran();

create or replace function public.lomba_trg_seri()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_sesi  text;
  v_mulai time;
  v_akhir time;
  v_tgl   date;
begin
  -- grup jadwal terbang: nama, tanggal, jam & kuota dihitung otomatis
  if new.sesi_id is not null then
    select s.nama, s.jam_mulai, s.jam_selesai, h.tanggal
      into v_sesi, v_mulai, v_akhir, v_tgl
      from public.lomba_sesi s join public.lomba_hari h on h.id = s.hari_id
     where s.id = new.sesi_id;
    if not found then
      raise exception 'SERI_TIDAK_VALID';
    end if;
    new.huruf := upper(btrim(coalesce(new.huruf, '')));
    if new.huruf = '' then
      raise exception 'DATA_TIDAK_LENGKAP';
    end if;
    new.nama        := 'Seri ' || v_sesi || ' · ' || new.huruf;
    new.tanggal     := v_tgl;
    new.jam_mulai   := v_mulai;
    new.jam_selesai := v_akhir;
    new.tutup := coalesce((select array_agg(distinct x order by x)
                             from unnest(new.tutup) x where x between 1 and new.kotak), '{}');
    new.kuota := greatest(0, new.kotak - cardinality(new.tutup));
    if tg_op = 'UPDATE'
       and (new.kotak is distinct from old.kotak or new.tutup is distinct from old.tutup)
       and exists (
         select 1 from public.lomba_pendaftaran p
          where p.seri_id = new.id and p.kotak is not null
            and p.status in ('menunggu', 'terkonfirmasi')
            and (p.kotak > new.kotak or p.kotak = any(new.tutup))) then
      raise exception 'KOTAK_TERISI';
    end if;
  end if;

  new.nama := btrim(coalesce(new.nama, ''));
  if new.nama = '' then
    raise exception 'DATA_TIDAK_LENGKAP';
  end if;
  if tg_op = 'UPDATE' and new.jenis is distinct from old.jenis
     and exists (select 1 from public.lomba_pendaftaran where seri_id = old.id) then
    raise exception 'SERI_ADA_PESERTA';
  end if;
  return new;
end;
$$;

drop trigger if exists lomba_seri_biu on public.lomba_seri;
create trigger lomba_seri_biu
  before insert or update on public.lomba_seri
  for each row execute function public.lomba_trg_seri();

-- Hari / seri diubah → nama, tanggal & jam grup ikut diperbarui
create or replace function public.lomba_trg_sesi_sinkron()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  new.nama := btrim(coalesce(new.nama, ''));
  if new.nama = '' then
    raise exception 'DATA_TIDAK_LENGKAP';
  end if;
  return new;
end;
$$;

create or replace function public.lomba_trg_sesi_setelah()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_table_name = 'lomba_hari' then
    update public.lomba_seri g set sesi_id = g.sesi_id
      from public.lomba_sesi s where s.id = g.sesi_id and s.hari_id = new.id;
  else
    update public.lomba_seri set sesi_id = sesi_id where sesi_id = new.id;
  end if;
  return null;
end;
$$;

drop trigger if exists lomba_hari_biu on public.lomba_hari;
create trigger lomba_hari_biu before insert or update on public.lomba_hari
  for each row execute function public.lomba_trg_sesi_sinkron();
drop trigger if exists lomba_hari_au on public.lomba_hari;
create trigger lomba_hari_au after update on public.lomba_hari
  for each row execute function public.lomba_trg_sesi_setelah();
drop trigger if exists lomba_sesi_biu on public.lomba_sesi;
create trigger lomba_sesi_biu before insert or update on public.lomba_sesi
  for each row execute function public.lomba_trg_sesi_sinkron();
drop trigger if exists lomba_sesi_au on public.lomba_sesi;
create trigger lomba_sesi_au after update on public.lomba_sesi
  for each row execute function public.lomba_trg_sesi_setelah();


-- ---------------------------------------------------------------------
-- BAGIAN 5 · FUNGSI PUBLIK (dipanggil halaman pendaftaran)
-- ---------------------------------------------------------------------

-- Info event, harga, jadwal seri + sisa kuota (tanpa data pribadi peserta)
create or replace function public.lomba_info_publik()
returns json
language sql
stable
security definer
set search_path = public
as $$
  with st as (
    select * from public.lomba_pengaturan where id = 1
  ),
  hit as (
    select seri_id, count(*) filter (where status in ('menunggu', 'terkonfirmasi')) as terisi
    from public.lomba_pendaftaran
    group by seri_id
  )
  select json_build_object(
    'event', (
      select json_build_object(
        'nama_event', nama_event,
        'penyelenggara', penyelenggara,
        'lokasi', lokasi,
        'info', info,
        'wa_admin', wa_admin,
        'bank_nama', bank_nama,
        'bank_no_rek', bank_no_rek,
        'bank_atas_nama', bank_atas_nama,
        'pendaftaran_buka', pendaftaran_buka and (batas_daftar is null or now() <= batas_daftar),
        'batas_daftar', batas_daftar,
        'tampilkan_peserta', tampilkan_peserta,
        'logo_url', logo_url,
        'bg_url', bg_url
      ) from st
    ),
    'hari', coalesce((
      select json_agg(json_build_object('id', h.id, 'nama', h.nama, 'tanggal', h.tanggal, 'urutan', h.urutan)
             order by h.tanggal nulls last, h.urutan, h.id)
      from public.lomba_hari h
    ), '[]'::json),
    'sesi', coalesce((
      select json_agg(json_build_object('id', s.id, 'hari_id', s.hari_id, 'nama', s.nama,
                                        'jam_mulai', s.jam_mulai, 'jam_selesai', s.jam_selesai, 'urutan', s.urutan)
             order by s.jam_mulai nulls last, s.urutan, s.id)
      from public.lomba_sesi s
    ), '[]'::json),
    'jenis', coalesce((
      select json_agg(json_build_object(
               'kode', j.kode, 'nama', j.nama, 'harga', j.harga,
               'prefix', j.prefix, 'aktif', j.aktif)
             order by j.urutan, j.nama)
      from public.lomba_jenis j
    ), '[]'::json),
    'seri', coalesce((
      select json_agg(json_build_object(
               'id', s.id, 'jenis', s.jenis, 'nama', s.nama, 'tanggal', s.tanggal,
               'jam_mulai', s.jam_mulai, 'jam_selesai', s.jam_selesai,
               'kuota', s.kuota, 'aktif', s.aktif, 'catatan', s.catatan,
               'sesi_id', s.sesi_id, 'huruf', s.huruf, 'kotak', s.kotak, 'tutup', s.tutup,
               'terisi', coalesce(h.terisi, 0),
               -- kotak terisi selalu tampil; nomor hanya untuk yang sudah terkonfirmasi
               'isi', (select coalesce(json_agg(json_build_object('kotak', p.kotak, 'status', p.status,
                                                                  'nomor', case when p.status = 'terkonfirmasi' then p.nomor_layangan end)
                                                order by p.kotak), '[]'::json)
                         from public.lomba_pendaftaran p
                        where p.seri_id = s.id and p.kotak is not null
                          and p.status in ('menunggu', 'terkonfirmasi')),
               -- nama sekha & alamat (pop-up saat nomor diklik) hanya bila opsi "tampilkan peserta" aktif
               'peserta', case when (select tampilkan_peserta from st) then (
                   select coalesce(json_agg(json_build_object('kotak', p.kotak, 'nomor', p.nomor_layangan,
                                                              'sekha', p.nama_sekha, 'alamat', p.alamat)
                                            order by p.kotak), '[]'::json)
                   from public.lomba_pendaftaran p
                   where p.seri_id = s.id and p.kotak is not null and p.status = 'terkonfirmasi'
                 ) end)
             order by s.tanggal nulls last, s.jam_mulai nulls last, s.urutan, s.id)
      from public.lomba_seri s
      left join hit h on h.seri_id = s.id
    ), '[]'::json),
    'waktu_server', now()
  );
$$;

-- Simpan pendaftaran baru (status selalu "menunggu" verifikasi)
drop function if exists public.lomba_daftar(text, bigint, text, text, text, text, text, text, uuid);
drop function if exists public.lomba_daftar(text, bigint, text, text, text, text, text, text, uuid, integer);
create or replace function public.lomba_daftar(
  p_jenis          text,
  p_seri_id        bigint,
  p_nama_sekha     text,
  p_alamat         text,
  p_no_wa          text,
  p_nama_rekening  text,
  p_bukti_path     text,
  p_bukti_hash     text default null,
  p_client_ref     uuid default null,
  p_harga          integer default null,
  p_nomor_layangan text default null
)
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
  v_set    public.lomba_pengaturan%rowtype;
  v_jenis  public.lomba_jenis%rowtype;
  v_seri   public.lomba_seri%rowtype;
  v_row    public.lomba_pendaftaran%rowtype;
  v_wa     text;
  v_ip     text;
  v_iphash text;
  v_ada    boolean;
  v_nomor  text;
  v_con    text;
begin
  -- kirim ulang (mis. koneksi putus) → kembalikan pendaftaran yang sama, tidak dobel
  if p_client_ref is not null then
    select * into v_row from public.lomba_pendaftaran where client_ref = p_client_ref;
    if found then
      return json_build_object('kode', v_row.kode, 'status', v_row.status, 'harga', v_row.harga,
                               'created_at', v_row.created_at, 'no_wa', v_row.no_wa,
                               'jenis', v_row.jenis, 'seri_id', v_row.seri_id, 'nama_sekha', v_row.nama_sekha,
                               'nomor_layangan', v_row.nomor_layangan, 'kotak', v_row.kotak);
    end if;
  end if;

  select * into v_set from public.lomba_pengaturan where id = 1;
  if not found or not v_set.pendaftaran_buka
     or (v_set.batas_daftar is not null and now() > v_set.batas_daftar) then
    raise exception 'PENDAFTARAN_DITUTUP';
  end if;

  select * into v_jenis from public.lomba_jenis where kode = p_jenis;
  if not found or not v_jenis.aktif then
    raise exception 'JENIS_TIDAK_VALID';
  end if;

  -- harga yang dilihat peserta harus sama dengan harga saat ini
  if p_harga is not null and p_harga <> v_jenis.harga then
    raise exception 'HARGA_BERUBAH';
  end if;

  select * into v_seri from public.lomba_seri where id = p_seri_id;
  if not found or v_seri.jenis <> p_jenis or not v_seri.aktif or v_seri.sesi_id is null then
    raise exception 'SERI_TIDAK_VALID';
  end if;

  -- nomor layangan milik peserta: angka 1–6 digit, unik per jenis
  v_nomor := btrim(coalesce(p_nomor_layangan, ''));
  if v_nomor !~ '^[0-9]{1,6}$' then
    raise exception 'NOMOR_TIDAK_VALID';
  end if;
  v_nomor := coalesce(nullif(ltrim(v_nomor, '0'), ''), '0');
  if exists (select 1 from public.lomba_pendaftaran
              where jenis = p_jenis and nomor_layangan = v_nomor
                and status in ('menunggu', 'terkonfirmasi')) then
    raise exception 'NOMOR_DIPAKAI';
  end if;

  if char_length(btrim(coalesce(p_nama_sekha, ''))) not between 2 and 120
     or char_length(btrim(coalesce(p_alamat, ''))) not between 3 and 300
     or char_length(btrim(coalesce(p_nama_rekening, ''))) not between 2 and 120 then
    raise exception 'DATA_TIDAK_LENGKAP';
  end if;

  v_wa := public.lomba_normalisasi_wa(p_no_wa);
  if v_wa is null then
    raise exception 'WA_TIDAK_VALID';
  end if;

  if p_bukti_path is null
     or p_bukti_path !~ '^bukti/[0-9a-f-]{36}\.(jpg|jpeg|png|webp|pdf)$' then
    raise exception 'BUKTI_TIDAK_VALID';
  end if;

  -- file bukti harus benar-benar sudah terunggah ke Storage
  begin
    select exists (select 1 from storage.objects
                   where bucket_id = 'lomba-bukti' and name = p_bukti_path) into v_ada;
  exception when others then
    v_ada := true;   -- bila Storage tidak bisa dibaca, jangan blokir pendaftaran
  end;
  if not v_ada then
    raise exception 'BUKTI_TIDAK_VALID';
  end if;

  -- rem anti-spam: maks 15 pendaftaran per nomor WA per jam
  if (select count(*) from public.lomba_pendaftaran
      where no_wa = v_wa and created_at > now() - interval '1 hour') >= 15 then
    raise exception 'TERLALU_BANYAK';
  end if;

  -- rem anti-spam: maks 30 pendaftaran per jaringan (IP) per 10 menit
  begin
    v_ip := nullif(btrim(split_part(coalesce(
              current_setting('request.headers', true)::json ->> 'cf-connecting-ip',
              current_setting('request.headers', true)::json ->> 'x-forwarded-for',
              current_setting('request.headers', true)::json ->> 'x-real-ip', ''), ',', 1)), '');
  exception when others then
    v_ip := null;
  end;
  if v_ip is not null then
    v_iphash := left(encode(sha256(convert_to('lomba:' || v_ip, 'UTF8')), 'hex'), 16);
    if (select count(*) from public.lomba_pendaftaran
        where ip_hash = v_iphash and created_at > now() - interval '10 minutes') >= 30 then
      raise exception 'TERLALU_BANYAK';
    end if;
  end if;

  insert into public.lomba_pendaftaran
    (client_ref, jenis, seri_id, nama_sekha, alamat, no_wa, nama_rekening,
     bukti_path, bukti_hash, harga, status, ip_hash, nomor_layangan)
  values
    (p_client_ref, p_jenis, p_seri_id, p_nama_sekha, p_alamat, v_wa, p_nama_rekening,
     p_bukti_path, left(p_bukti_hash, 128), v_jenis.harga, 'menunggu', v_iphash, v_nomor)
  returning * into v_row;

  return json_build_object('kode', v_row.kode, 'status', v_row.status, 'harga', v_row.harga,
                           'created_at', v_row.created_at, 'no_wa', v_row.no_wa,
                           'jenis', v_row.jenis, 'seri_id', v_row.seri_id, 'nama_sekha', v_row.nama_sekha,
                           'nomor_layangan', v_row.nomor_layangan, 'kotak', v_row.kotak);
exception
  when unique_violation then
    get stacked diagnostics v_con = constraint_name;
    if p_client_ref is not null then
      select * into v_row from public.lomba_pendaftaran where client_ref = p_client_ref;
      if found then
        return json_build_object('kode', v_row.kode, 'status', v_row.status, 'harga', v_row.harga,
                                 'created_at', v_row.created_at, 'no_wa', v_row.no_wa,
                                 'jenis', v_row.jenis, 'seri_id', v_row.seri_id, 'nama_sekha', v_row.nama_sekha,
                                 'nomor_layangan', v_row.nomor_layangan, 'kotak', v_row.kotak);
      end if;
    end if;
    if coalesce(v_con, '') like '%nomor%' then
      raise exception 'NOMOR_DIPAKAI';
    end if;
    if coalesce(v_con, '') like '%kotak%' then
      raise exception 'KUOTA_PENUH';
    end if;
    raise exception 'BUKTI_TIDAK_VALID';
end;
$$;

-- Cek nomor layangan masih bisa dipakai untuk jenis tertentu (true = tersedia)
create or replace function public.lomba_cek_nomor(p_jenis text, p_nomor text)
returns boolean
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v text := btrim(coalesce(p_nomor, ''));
begin
  if v !~ '^[0-9]{1,6}$' then
    return false;
  end if;
  v := coalesce(nullif(ltrim(v, '0'), ''), '0');
  return not exists (select 1 from public.lomba_pendaftaran
                      where jenis = p_jenis and nomor_layangan = v
                        and status in ('menunggu', 'terkonfirmasi'));
end;
$$;

-- Data konfirmasi untuk link PDF yang dikirim lewat WhatsApp (#tiket/KODE).
-- Hanya pendaftaran TERKONFIRMASI; nomor WA disamarkan.
create or replace function public.lomba_tiket(p_kode text)
returns json
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_kode text := upper(btrim(coalesce(p_kode, '')));
begin
  if v_kode !~ '^LL-[0-9A-Z]{6}$' then
    return null;
  end if;
  return (
    select json_build_object(
      'event', (select json_build_object('nama_event', st.nama_event, 'penyelenggara', st.penyelenggara,
                                         'lokasi', st.lokasi, 'logo_url', st.logo_url)
                  from public.lomba_pengaturan st where st.id = 1),
      'kode', p.kode, 'nomor_layangan', p.nomor_layangan, 'jenis', j.nama,
      'nama_sekha', p.nama_sekha, 'alamat', p.alamat,
      'no_wa', '0' || substr(p.no_wa, 3, 3) || '-****-' || right(p.no_wa, 4),
      'kotak', p.kotak, 'seri_nama', s.nama, 'huruf', s.huruf, 'sesi_nama', ss.nama, 'hari', h.nama,
      'tanggal', s.tanggal, 'jam_mulai', s.jam_mulai, 'jam_selesai', s.jam_selesai)
    from public.lomba_pendaftaran p
    join public.lomba_jenis j on j.kode = p.jenis
    join public.lomba_seri s on s.id = p.seri_id
    left join public.lomba_sesi ss on ss.id = s.sesi_id
    left join public.lomba_hari h on h.id = ss.hari_id
    where p.kode = v_kode and p.status = 'terkonfirmasi'
  );
end;
$$;

-- Cek status pendaftaran berdasarkan nomor WA (data terbatas)
create or replace function public.lomba_cek_status(p_no_wa text)
returns json
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_wa text := public.lomba_normalisasi_wa(p_no_wa);
begin
  if v_wa is null then
    raise exception 'WA_TIDAK_VALID';
  end if;
  return coalesce((
    select json_agg(x order by x.created_at desc)
    from (
      select p.kode, p.jenis, j.nama as jenis_nama, p.nama_sekha, p.status,
             p.nomor_layangan, p.kotak, p.alasan_tolak, p.harga, p.created_at,
             s.nama as seri_nama, s.tanggal, s.jam_mulai, s.jam_selesai
      from public.lomba_pendaftaran p
      join public.lomba_jenis j on j.kode = p.jenis
      join public.lomba_seri s on s.id = p.seri_id
      where p.no_wa = v_wa
      order by p.created_at desc
      limit 50
    ) x
  ), '[]'::json);
end;
$$;


-- ---------------------------------------------------------------------
-- BAGIAN 6 · FUNGSI ADMIN
-- ---------------------------------------------------------------------

-- Pemeriksaan kesehatan setup (dipakai menu Pengaturan di dashboard)
create or replace function public.lomba_cek_setup()
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
  v_bucket boolean;
  v_media  boolean;
  v_pol    int;
  v_rt     boolean;
  v_admin  int;
begin
  if not public.lomba_is_admin() then
    raise exception 'BUKAN_ADMIN';
  end if;
  begin
    select exists (select 1 from storage.buckets where id = 'lomba-bukti') into v_bucket;
  exception when others then
    v_bucket := null;
  end;
  begin
    select exists (select 1 from storage.buckets where id = 'lomba-media') into v_media;
  exception when others then
    v_media := null;
  end;
  select count(*) into v_pol from pg_policies
   where schemaname = 'storage' and tablename = 'objects' and policyname like 'lomba_bukti_%';
  select exists (select 1 from pg_publication_tables
                  where pubname = 'supabase_realtime' and schemaname = 'public'
                    and tablename = 'lomba_pendaftaran') into v_rt;
  select count(*) into v_admin from public.lomba_admin;
  return json_build_object('bucket', v_bucket, 'media', v_media, 'storage_policies', v_pol,
                           'realtime', v_rt, 'admins', v_admin, 'versi', '2.0');
end;
$$;

-- Tutup / buka satu kotak di grup jadwal (atomik, aman bila 2 admin mengubah bersamaan)
create or replace function public.lomba_atur_kotak(p_seri_id bigint, p_kotak int, p_tutup boolean)
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
  v public.lomba_seri%rowtype;
begin
  if not public.lomba_is_admin() then
    raise exception 'BUKAN_ADMIN';
  end if;
  update public.lomba_seri
     set tutup = case when p_tutup then array_append(array_remove(tutup, p_kotak), p_kotak)
                      else array_remove(tutup, p_kotak) end
   where id = p_seri_id
  returning * into v;
  if not found then
    raise exception 'SERI_TIDAK_VALID';
  end if;
  return row_to_json(v);
end;
$$;

-- Hapus semua pendaftaran & reset nomor urut (dipakai setelah uji coba).
-- Mengembalikan daftar file bukti agar dashboard ikut menghapusnya dari Storage.
create or replace function public.lomba_reset_data()
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
  v_paths json;
  v_n     int;
begin
  if not public.lomba_is_admin() then
    raise exception 'BUKAN_ADMIN';
  end if;
  select coalesce(json_agg(bukti_path), '[]'::json) into v_paths
    from public.lomba_pendaftaran where bukti_path is not null;
  delete from public.lomba_pendaftaran where id is not null;
  get diagnostics v_n = row_count;
  update public.lomba_jenis set nomor_terakhir = 0 where kode is not null;
  return json_build_object('dihapus', v_n, 'bukti_paths', v_paths);
end;
$$;


-- ---------------------------------------------------------------------
-- BAGIAN 7 · KEAMANAN (RLS): data peserta hanya bisa dibaca admin
-- ---------------------------------------------------------------------
alter table public.lomba_admin        enable row level security;
alter table public.lomba_pengaturan   enable row level security;
alter table public.lomba_jenis        enable row level security;
alter table public.lomba_seri         enable row level security;
alter table public.lomba_pendaftaran  enable row level security;
alter table public.lomba_hari         enable row level security;
alter table public.lomba_sesi         enable row level security;

drop policy if exists lomba_admin_kelola on public.lomba_hari;
create policy lomba_admin_kelola on public.lomba_hari
  for all to authenticated
  using ((select public.lomba_is_admin()))
  with check ((select public.lomba_is_admin()));

drop policy if exists lomba_admin_kelola on public.lomba_sesi;
create policy lomba_admin_kelola on public.lomba_sesi
  for all to authenticated
  using ((select public.lomba_is_admin()))
  with check ((select public.lomba_is_admin()));

drop policy if exists lomba_admin_kelola on public.lomba_pengaturan;
create policy lomba_admin_kelola on public.lomba_pengaturan
  for all to authenticated
  using ((select public.lomba_is_admin()))
  with check ((select public.lomba_is_admin()));

drop policy if exists lomba_admin_kelola on public.lomba_jenis;
create policy lomba_admin_kelola on public.lomba_jenis
  for all to authenticated
  using ((select public.lomba_is_admin()))
  with check ((select public.lomba_is_admin()));

drop policy if exists lomba_admin_kelola on public.lomba_seri;
create policy lomba_admin_kelola on public.lomba_seri
  for all to authenticated
  using ((select public.lomba_is_admin()))
  with check ((select public.lomba_is_admin()));

drop policy if exists lomba_admin_kelola on public.lomba_pendaftaran;
create policy lomba_admin_kelola on public.lomba_pendaftaran
  for all to authenticated
  using ((select public.lomba_is_admin()))
  with check ((select public.lomba_is_admin()));


-- ---------------------------------------------------------------------
-- BAGIAN 8 · HAK AKSES (GRANT) — wajib sejak aturan baru Supabase 2026
--   anon (pengunjung)  : hanya boleh memanggil fungsi publik
--   authenticated      : akses tabel, tetap dibatasi RLS → hanya admin
-- ---------------------------------------------------------------------
revoke all on table public.lomba_admin, public.lomba_pengaturan, public.lomba_jenis,
                    public.lomba_seri, public.lomba_pendaftaran,
                    public.lomba_hari, public.lomba_sesi from anon;
revoke all on table public.lomba_admin from authenticated;
grant select, insert, update, delete
  on table public.lomba_pengaturan, public.lomba_jenis, public.lomba_seri, public.lomba_pendaftaran,
           public.lomba_hari, public.lomba_sesi
  to authenticated;
grant select, insert, update, delete
  on table public.lomba_admin, public.lomba_pengaturan, public.lomba_jenis,
           public.lomba_seri, public.lomba_pendaftaran, public.lomba_hari, public.lomba_sesi
  to service_role;
grant usage, select on sequence public.lomba_seri_id_seq, public.lomba_hari_id_seq, public.lomba_sesi_id_seq
  to authenticated, service_role;

revoke all on function public.lomba_trg_pendaftaran() from public, anon, authenticated;
revoke all on function public.lomba_trg_seri() from public, anon, authenticated;
revoke all on function public.lomba_trg_sesi_sinkron() from public, anon, authenticated;
revoke all on function public.lomba_trg_sesi_setelah() from public, anon, authenticated;
revoke all on function public.lomba_cek_setup() from public, anon;
revoke all on function public.lomba_reset_data() from public, anon;
revoke all on function public.lomba_atur_kotak(bigint, int, boolean) from public, anon;
revoke all on function public.lomba_kode_baru() from public, anon;

grant execute on function public.lomba_info_publik() to anon, authenticated;
grant execute on function public.lomba_daftar(text, bigint, text, text, text, text, text, text, uuid, integer, text)
  to anon, authenticated;
grant execute on function public.lomba_cek_nomor(text, text) to anon, authenticated;
grant execute on function public.lomba_cek_status(text) to anon, authenticated;
grant execute on function public.lomba_tiket(text) to anon, authenticated;
grant execute on function public.lomba_is_admin() to anon, authenticated;
grant execute on function public.lomba_normalisasi_wa(text) to anon, authenticated;
grant execute on function public.lomba_kode_baru() to authenticated;
grant execute on function public.lomba_cek_setup() to authenticated;
grant execute on function public.lomba_reset_data() to authenticated;
grant execute on function public.lomba_atur_kotak(bigint, int, boolean) to authenticated;


-- ---------------------------------------------------------------------
-- BAGIAN 9 · STORAGE BUKTI TRANSFER (bucket privat, maks 3 MB per file)
--   Pengunjung hanya bisa MENGUNGGAH ke folder bukti/, tidak bisa melihat.
--   Admin bisa melihat & menghapus.
-- ---------------------------------------------------------------------
do $$
begin
  insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
  values ('lomba-bukti', 'lomba-bukti', false, 3145728,
          array['image/jpeg', 'image/png', 'image/webp', 'application/pdf'])
  on conflict (id) do update
    set public = false,
        file_size_limit = excluded.file_size_limit,
        allowed_mime_types = excluded.allowed_mime_types;
exception when others then
  raise notice 'Bucket lomba-bukti tidak bisa dibuat lewat SQL (%). Buat manual di menu Storage.', sqlerrm;
end;
$$;

do $$
begin
  drop policy if exists "lomba_bukti_upload" on storage.objects;
  create policy "lomba_bukti_upload" on storage.objects
    for insert to anon, authenticated
    with check (bucket_id = 'lomba-bukti' and (storage.foldername(name))[1] = 'bukti');

  drop policy if exists "lomba_bukti_admin_baca" on storage.objects;
  create policy "lomba_bukti_admin_baca" on storage.objects
    for select to authenticated
    using (bucket_id = 'lomba-bukti' and (select public.lomba_is_admin()));

  drop policy if exists "lomba_bukti_admin_hapus" on storage.objects;
  create policy "lomba_bukti_admin_hapus" on storage.objects
    for delete to authenticated
    using (bucket_id = 'lomba-bukti' and (select public.lomba_is_admin()));
exception when others then
  raise notice 'Policy storage tidak bisa dibuat lewat SQL (%). Buat manual (lihat panduan).', sqlerrm;
end;
$$;

-- Logo & gambar latar halaman peserta: bucket PUBLIK (siapa saja bisa melihat),
-- hanya admin yang bisa mengunggah, mengganti & menghapus. Maks 5 MB per file.
do $$
begin
  insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
  values ('lomba-media', 'lomba-media', true, 5242880,
          array['image/jpeg', 'image/png', 'image/webp'])
  on conflict (id) do update
    set public = true,
        file_size_limit = excluded.file_size_limit,
        allowed_mime_types = excluded.allowed_mime_types;
exception when others then
  raise notice 'Bucket lomba-media tidak bisa dibuat lewat SQL (%). Buat manual di menu Storage (Public).', sqlerrm;
end;
$$;

do $$
begin
  drop policy if exists "lomba_media_admin_baca" on storage.objects;
  create policy "lomba_media_admin_baca" on storage.objects
    for select to authenticated
    using (bucket_id = 'lomba-media' and (select public.lomba_is_admin()));

  drop policy if exists "lomba_media_admin_upload" on storage.objects;
  create policy "lomba_media_admin_upload" on storage.objects
    for insert to authenticated
    with check (bucket_id = 'lomba-media' and (select public.lomba_is_admin()));

  drop policy if exists "lomba_media_admin_hapus" on storage.objects;
  create policy "lomba_media_admin_hapus" on storage.objects
    for delete to authenticated
    using (bucket_id = 'lomba-media' and (select public.lomba_is_admin()));
exception when others then
  raise notice 'Policy storage media tidak bisa dibuat lewat SQL (%).', sqlerrm;
end;
$$;


-- ---------------------------------------------------------------------
-- BAGIAN 10 · REALTIME, ADMIN & DATA AWAL
-- ---------------------------------------------------------------------

-- Dashboard admin ter-update otomatis saat ada pendaftaran baru
do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime')
     and not exists (select 1 from pg_publication_tables
                     where pubname = 'supabase_realtime' and schemaname = 'public'
                       and tablename = 'lomba_pendaftaran') then
    execute 'alter publication supabase_realtime add table public.lomba_pendaftaran';
  end if;
exception when others then
  raise notice 'Realtime tidak aktif (%). Dashboard tetap jalan dengan refresh berkala.', sqlerrm;
end;
$$;

-- >>> EMAIL ADMIN — ganti/tambah bila perlu (harus sama dengan user di Authentication)
insert into public.lomba_admin (email) values
  ('adeyudistira62@gmail.com')
on conflict (email) do nothing;

-- Pengaturan awal + template pesan WhatsApp (bisa diubah dari dashboard)
insert into public.lomba_pengaturan (id, nama_event, template_wa_konfirmasi, template_wa_tolak)
values (
  1,
  'Lomba Layangan Tradisional 2026',
$tpl$Om Swastyastu 🙏

*KONFIRMASI PENDAFTARAN*
*{nama_event}*

Pembayaran sudah kami terima. Layangan Anda resmi *TERDAFTAR*.

• Jenis layangan: {jenis}
• Nama sekha: {nama_sekha}
• Alamat: {alamat}
• Nomor WA: {no_wa}
• Nomor layangan: *{nomor_layangan}*
• Seri & grup: {seri}
• Jadwal terbang: {jadwal}

Kode pendaftaran: {kode}
Mohon nomor layangan dipasang pada layangan dan hadir tepat waktu sesuai jadwal seri.

Suksma 🙏
{penyelenggara}$tpl$,
$tpl$Om Swastyastu 🙏

Mohon maaf, pendaftaran layangan *{jenis}* atas nama *{nama_sekha}* (kode {kode}) untuk {nama_event} *belum dapat kami konfirmasi*.

Alasan: {alasan}

Silakan balas pesan ini bila ada pertanyaan atau untuk mengirim ulang bukti transfer.

Suksma 🙏
{penyelenggara}$tpl$
)
on conflict (id) do nothing;

-- Jenis layangan, harga, seri & kuota TIDAK diisi otomatis:
-- semuanya dibuat manual oleh admin di dashboard (menu Jenis Layangan
-- dan Seri & Jadwal). Menjalankan ulang file ini tidak menambah atau
-- memunculkan kembali jenis yang sudah dihapus admin.


-- ---------------------------------------------------------------------
-- BAGIAN 11 · CEK SETUP — semua baris sebaiknya ✅
-- ---------------------------------------------------------------------
select no, cek, hasil from (values
  (1, 'Tabel & fungsi',
      case when to_regprocedure('public.lomba_daftar(text,bigint,text,text,text,text,text,text,uuid,integer,text)') is not null
            and to_regclass('public.lomba_sesi') is not null
           then '✅ OK' else '❌ Gagal' end),
  (2, 'Bucket bukti transfer (Storage)',
      case when exists (select 1 from storage.buckets where id = 'lomba-bukti')
           then '✅ OK' else '❌ Belum ada — buat manual (lihat panduan)' end),
  (3, 'Policy Storage (3 aturan)',
      case when (select count(*) from pg_policies
                 where schemaname = 'storage' and tablename = 'objects'
                   and policyname like 'lomba_bukti_%') = 3
           then '✅ OK' else '❌ Belum lengkap — buat manual (lihat panduan)' end),
  (4, 'Realtime dashboard',
      case when exists (select 1 from pg_publication_tables
                        where pubname = 'supabase_realtime' and schemaname = 'public'
                          and tablename = 'lomba_pendaftaran')
           then '✅ OK' else '⚠️ Tidak aktif — dashboard tetap jalan (refresh berkala)' end),
  (6, 'Bucket logo & latar (Storage)',
      case when exists (select 1 from storage.buckets where id = 'lomba-media' and public)
           then '✅ OK' else '❌ Belum ada — buat bucket Public "lomba-media" (lihat panduan)' end),
  (5, 'Email admin',
      coalesce((select '✅ ' || string_agg(email, ', ') from public.lomba_admin), '❌ Belum ada'))
) as t(no, cek, hasil)
order by no;
